### ISSUE TITLE
ELB: Error "The action DescribeLoadBalancers is not valid for this web service."

### ISSUE THREAD

**Issue by subnetmarco** [boto/boto#1282]
I'm getting the following error when executing the following code:

``` python
region = boto.ec2.get_region('us-east-1')
elb_conn = boto.ec2.elb.ELBConnection(aws_access_key_id = accessKey, aws_secret_access_key = accessSecret, region=region)
elb_conn.get_all_load_balancers()
```

The error is:

```
File "/Library/Python/2.7/site-packages/boto/ec2/elb/__init__.py", line 138, in get_all_load_balancers
    [('member', LoadBalancer)])
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 1003, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidAction</Code><Message>The action DescribeLoadBalancers is not valid for this web service.</Message></Error></Errors><RequestID>90bfbc36-febb-42f9-ace9-2c582765b938</RequestID></Response>
```

**Comment by sameergautam** [comment]
I'm also getting similar issue with Launch Configuration while using Ansible's [`ec2_lc`](http://docs.ansible.com/ansible/latest/modules/ec2_lc_module.html) module.

<details>
<summary>Backtrace</summary>

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/b_/g8r_f0cx0bdb0vb5c2m55lth0000gn/T/ansible_jVpiEI/ansible_module_ec2_lc.py", line 498, in create_launch_config
    launch_configs = connection.describe_launch_configurations(LaunchConfigurationNames=[name]).get('LaunchConfigurations')
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidAction) when calling the DescribeLaunchConfigurations operation: The action DescribeLaunchConfigurations is not valid for this web service.

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "error": {
        "code": "InvalidAction",
        "message": "The action DescribeLaunchConfigurations is not valid for this web service."
    }
...
```
</details>

<details>
<summary>Ansible Play </summary>

```yaml
- name: Create Launch Configuration
  ec2_lc:
    region: "{{ region }}"
    name: "ansible-launch-config"
    image_id: "{{ image_id }}"
    instance_type: "{{ instance_type }}"
    security_groups: "{{ security_groups }}"
    state: present

```
</details>
<details>
<summary>System Details</summary>

```
ansible --version
ansible 2.5.0
```
```
boto version: 
import boto; print(boto.__version__)
2.48.0
```
