### ISSUE TITLE
could not launch instance using python2.6 and boto 2.0b4

### ISSUE THREAD

**Issue by jumping** [boto/boto#148]
Traceback (most recent call last):
  File "launch_instance", line 130, in <module>
    ami = ec2.get_image(options.ami_id)
  File "build/bdist.linux-i686/egg/boto/ec2/connection.py", line 213, in get_image
  File "build/bdist.linux-i686/egg/boto/ec2/connection.py", line 154, in get_all_images
  File "build/bdist.linux-i686/egg/boto/connection.py", line 599, in get_list
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>RequestExpired</Code><Message>Request has expired. Timestamp date is 2011-03-26T23:22:53Z</Message></Error></Errors><RequestID>c6512d25-c974-4f58-9b50-ffe70bcb66ea</RequestID></Response>

**Comment by Sreevani543** [comment]
Hi can I know how you got this issue resolved.
