### ISSUE TITLE
Dynamodb save with float raises exception DynamoDBNumberError

### ISSUE THREAD

**Issue by ushma** [boto/boto#1531]
with python 2.7 and boto 2.9.4

```
item = Item.get_item(key='key')
item['number'] = 26.34
item.save()
```

raises:

```
Traceback (most recent call last):
  File "boto.py", line 9, in <module>
    item.save()
  File "/home/user/boto/boto/dynamodb2/items.py", line 365, in save
    final_data = self.prepare_full()
  File "/home/user/boto/boto/dynamodb2/items.py", line 268, in prepare_full
    final_data[key] = self._dynamizer.encode(value)
  File "/home/user/boto/boto/dynamodb/types.py", line 234, in encode
    return {dynamodb_type: encoder(attr)}
  File "/home/user/boto/boto/dynamodb/types.py", line 250, in _encode_n
    raise DynamoDBNumberError(msg)
boto.dynamodb.exceptions.DynamoDBNumberError: BotoClientError: Inexact numeric for `26.34`
```

It appears that the internals are converting floats to Decimal datatype with 38 digits of precision.
https://github.com/boto/boto/blob/develop/boto/dynamodb/types.py#L243

However, aws docs suggest that numbers can have up to 38 digits after decimal points, but not to convert all the floats to that precision.
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DataModel.html#DataModelDataTypes

**Comment by craiga** [comment]
For what it's worth, I found that numbers larger than ~1048575.4 save just fine. Numbers less than this encounter this error.

    >>> t
    <boto.dynamodb2.table.Table object at 0x1004a2450>
    >>> t.put_item({'number': 1048575.5}, overwrite=True)
    True
    >>> t.put_item({'test', 'number': 1048575.4}, overwrite=True)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/virtual-environment/lib/python2.7/site-packages/boto/dynamodb2/table.py", line 821, in put_item
        return item.save(overwrite=overwrite)
      File "/virtualenv/lib/python2.7/site-packages/boto/dynamodb2/items.py", line 448, in save
        final_data = self.prepare_full()
      File "/virtualenv/lib/python2.7/site-packages/boto/dynamodb2/items.py", line 329, in prepare_full
        final_data[key] = self._dynamizer.encode(value)
      File "/virtualenv/lib/python2.7/site-packages/boto/dynamodb/types.py", line 279, in encode
        return {dynamodb_type: encoder(attr)}
      File "/virtualenv/lib/python2.7/site-packages/boto/dynamodb/types.py", line 295, in _encode_n
        raise DynamoDBNumberError(msg)
    boto.dynamodb.exceptions.DynamoDBNumberError: BotoClientError: Inexact numeric for `1048575.4`
    None

This explains why the return value of `time.time()` saves to DynamoDB ([unless you're a time traveller to early January 1970](http://unixtimesta.mp/1048575)), but `1.234` doesn't.

**Comment by lbenitez000** [comment]
This is the same solution @depristo suggests, but as a monkey patch. If you are comfortable with allowing inexact representation of floats, then try this out.

https://gist.github.com/lbenitez000/85fb43e40a7839e13405

```Python
# Monkey patch Decimal's default Context to allow 
# inexact and rounded representation of floats
import decimal
from boto.dynamodb.types import DYNAMODB_CONTEXT
# Inhibit Inexact Exceptions
DYNAMODB_CONTEXT.traps[decimal.Inexact] = 0
# Inhibit Rounded Exceptions
DYNAMODB_CONTEXT.traps[decimal.Rounded] = 0
```

**Comment by joaoportela** [comment]
@craiga `1836016.789451258` doesn't save correctly.
