### ISSUE TITLE
could not authorize to amazon-elb/amazon-elb-sg

### ISSUE THREAD

**Issue by jumping** [boto/boto#1547]
> > > g=boto.ec2.securitygroup.SecurityGroup('amazon-elb-sg', 'amazon-elb')
> > > group.authorize('tcp', 80, 80, src_group=g)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Python/2.7/site-packages/boto-2.8.0-py2.7.egg/boto/ec2/securitygroup.py", line 184, in authorize
> > >     src_group_group_id)
> > >   File "/Library/Python/2.7/site-packages/boto-2.8.0-py2.7.egg/boto/ec2/connection.py", line 2459, in authorize_security_group
> > >     params, verb='POST')
> > >   File "/Library/Python/2.7/site-packages/boto-2.8.0-py2.7.egg/boto/connection.py", line 1081, in get_status
> > >     raise self.ResponseError(response.status, response.reason, body)
> > > boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
> > > <?xml version="1.0" encoding="UTF-8"?>
> > > <Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>Unable to find group 'amazon-elb/amazon-elb-sg'</Message></Error></Errors><RequestID>0878b850-0c8f-4bdb-b7f2-5b99ff331ff3</RequestID></Response>

**Comment by hypexr** [comment]
Any news on this?  Is there a way to authorize an ELB for a security group?
