### ISSUE TITLE
ResumableDownloadHandler failing 

### ISSUE THREAD

**Issue by glinscott** [boto/boto#1595]
It looks like the etag is expected to be initialized, but it's not initialized until the key is opened.

Repro script:

```
import boto
from boto.s3.resumable_download_handler import ResumableDownloadHandler
handler = ResumableDownloadHandler(num_retries=5)
conn = boto.connect_s3()
bucket = conn.get_bucket('mybucket')
k = boto.s3.key.Key(bucket)
k.key = 'my_key'
k.get_contents_to_filename('foo', res_download_handler=handler)
```

Exception

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 1615, in get_contents_to_filename
    response_headers=response_headers)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 1558, in get_contents_to_file
    version_id=version_id)
  File "/usr/lib/python2.6/site-packages/boto/s3/resumable_download_handler.py", line 280, in get_file
    torrent, version_id, hash_algs)
  File "/usr/lib/python2.6/site-packages/boto/s3/resumable_download_handler.py", line 208, in _attempt_resumable_download
    self._save_tracker_info(key)
  File "/usr/lib/python2.6/site-packages/boto/s3/resumable_download_handler.py", line 152, in _save_tracker_info
    self.etag_value_for_current_download = key.etag.strip('"\'')
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by acactown** [comment]
@glinscott I have the same error, I change one line code to fix them:

```python
import boto
from boto.s3.resumable_download_handler import ResumableDownloadHandler
handler = ResumableDownloadHandler(num_retries=5)
conn = boto.connect_s3()
bucket = conn.get_bucket('mybucket')
key = bucket.get_key('my_key')
print key.etag
key.get_contents_to_filename('foo', res_download_handler=handler)
```

Look over `key = bucket.get_key('my_key')`...  is the right way to get the key from a bucket

**Comment by hbbtstar** [comment]
hi @glinscott @acactown- is this still an issue? Just got this issue on codetriage so wondering if it can be closed, there's been no activity here for some time. Thanks!
