### ISSUE TITLE
Opsworks describe_instances fails with 400 despite providing stack_id and layer_id

### ISSUE THREAD

**Issue by airtonix** [boto/boto#1638]
I defined a stack with a name
I defined three layers : Application, Database, Load Balancer
I put one t1.micro `LoadBasedAutoscaling` instance into the Application layer. It is currently in the `stopped` state.

Then using the following snippet :

```
#~/bin/boto-test.py 
STACK_ID = 'A_VALID_STACK_ID'
LAYER_ID = None

# boto.set_stream_logger('boto')
opsworks = boto.connect_opsworks()

stacks = opsworks.describe_stacks(stack_ids=[STACK_ID, ])
print stacks.get("Stacks")[0].get("Name")

layers = opsworks.describe_layers(stack_id=STACK_ID)

for layer in layers.get('Layers', []):
    layer_id = layer.get('LayerId')
    layer_name = layer.get('Name')
    print "Instances for", layer_name
    instances = opsworks.describe_instances(stack_id=STACK_ID,
                                            layer_id=layer_id)
    for instance in instances.get("Instances"):
        print " "*4, instance.get("Hostname"), instance.get("InstanceId"), instance.get("InstanceType")
```
### What I Expect

I expect to get a json response that contains an either an empty list or the instances for just that stack.

```
$ pip freeze | grep boto
boto==2.9.9

$ python ./boto-test.py 
<INSTANCE_NAME>
Instances for Application
     otoroshi <INSTANCE_ID> t1.micro
Instances for Load Balancer
Instances for Database

```
### What I see

```
$ pip freeze | grep boto
boto==2.9.9

$ python ./boto-test.py 
<INSTANCE_NAME>
Instances for Application
Traceback (most recent call last):
  File "./boto-test.py", line 19, in <module>
    instances = opsworks.describe_instances(stack_id=STACK_ID, layer_id=layer_id)
  File "/usr/local/lib/python2.7/dist-packages/boto/opsworks/layer1.py", line 1028, in describe_instances
    body=json.dumps(params))
  File "/usr/local/lib/python2.7/dist-packages/boto/opsworks/layer1.py", line 1832, in make_request
    body=json_body)
boto.opsworks.exceptions.ValidationException: ValidationException: 400 Bad Request
{u'message': u'Please provide either one or more instance ID or one stack ID or one layer ID', u'__type': u'ValidationException'}
```

**Comment by bpolania** [comment]
This is an old issue but the documentation is still having issues:

[describeApps documentation](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-opsworks-2013-02-18.html#describeapps) still says 

> "You must specify at least one of the parameters."

This is really confusing because it implies that both parameters can be used, I suggest to change it to:

> "You must specify one (and only one) of the parameters."

or something similar.
