### ISSUE TITLE
CloudFront - CacheBehaviors Support

### ISSUE THREAD

**Issue by mathusiast** [boto/boto#1747]
It would be nice if boto will support setting cache behaviors for a distribution.
A simple setting such as forward query string is so crucial yet not supported.

http://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/PutConfig.html#PutConfig_RelatedActions

**Comment by karlgrz** [comment]
I also am very interested in this. I just forked boto to start work on this, hopefully I can get something working in a reasonable amount of time.

**Comment by karlgrz** [comment]
https://github.com/karlgrz/boto/commit/a82c39caeffa6f19703a3341b048f0c93fe4bfbc

Looking at the API version used in cloudfront package it is set to: '2010-11-01'

If I take a look at the API documentation for that version here:

http://docs.aws.amazon.com/AmazonCloudFront/2010-11-01/APIReference/GetConfig.html

None of the CacheBehaviors / DefaultCacheBehavior properties are coming back in the response (consistent with the output I was seeing in my initial tests). 

If I update to 2012-07-01 version of the API, everything appears to work properly.

I may be missing something completely off in cachebehavior.py (https://github.com/karlgrz/boto/blob/cachebehaviors/boto/cloudfront/cachebehavior.py#L338-L369) but it appears to be working properly, at least in my initial tests. I'm not very experienced with xml.sax so if there is a better way to handle that I'm all for suggestions.

I'd love some feedback to clean this up a bit before submitting a pull request. There's definitely some re-organization that can be done, but I just tried to follow the patterns in the rest of the project. Thanks!

**Comment by karlgrz** [comment]
OH! Also, I noticed that some of the properties were added in version 2013-09-27, but when I use that version I get this when I try get_distribution_config(id):

```
<?xml version="1.0"?>
<ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2013-09-27/"><Error><Type>Sender</Type><Code>IncompleteSignature</Code><Message>Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization=AWS MY_AWS_ACCESS_KEY_REDACTED:MY_AWS_SIGNATURE_REDACTED</Message></Error><RequestId>MY_REQUEST_ID_REDACTED</RequestId></ErrorResponse>
```

**Comment by karlgrz** [comment]
Bumping the version requires some additional (and probably breaking) changes to the DistributionConfig. I started implementing all that and have a bit of work to go.

**Comment by karlgrz** [comment]
https://github.com/karlgrz/boto/commit/fb2de09188a2ca3fd81405df346909a24417de5b

I've what looks like should be enough to get DefaultCacheBehaviors and an arbitrary amount of CacheBehaviors set on a DistributionConfig, but I can't figure out what I am doing wrong. I keep getting the following error when I try to create a distribution using the DefaultCacheBehavior:

```
Traceback (most recent call last):
  File "./boto-test.py", line 33, in <module>
    cf.create_distribution(comment="test",default_root_object="index.html",origin=origin, enabled=True, caller_reference=environment + "-ffef245b8fd243c5b819e5470e206329", default_cache_behavior=cache_behavior)
  File "/srv/boto/boto/cloudfront/__init__.py", line 175, in create_distribution
    return self._create_object(config, 'distribution', Distribution)
  File "/srv/boto/boto/cloudfront/__init__.py", line 141, in _create_object
    raise CloudFrontServerError(response.status, response.reason, body)
boto.cloudfront.exception.CloudFrontServerError: CloudFrontServerError: 400 Bad Request
<?xml version="1.0"?>
<ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2012-07-01/"><Error><Type>Sender</Type><Code>InvalidOrigin</Code><Message>The specified origin server does not exist or is not valid.</Message></Error><RequestId>dd188b13-b5ec-11e4-8105-dd20670c125b</RequestId></ErrorResponse>
```

Any help would be appreciated, I'd love to get this fully implemented. I feel like I'm about 90% there, just need a little help to get the rest of the way.
