### ISSUE TITLE
could not update cnames of a distribution

### ISSUE THREAD

**Issue by jumping** [boto/boto#1845]
I tried to update cnames of a distribution, but got error messages.

```
>>> cd.update(cnames=dis.cnames)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/boto-2.15.0-py2.7.egg/boto/cloudfront/distribution.py", line 359, in update
    self.etag = self.connection.set_distribution_config(self.id, self.etag, new_config)
  File "/Library/Python/2.7/site-packages/boto-2.15.0-py2.7.egg/boto/cloudfront/__init__.py", line 163, in set_distribution_config
    return self._set_config(distribution_id, etag, config)
  File "/Library/Python/2.7/site-packages/boto-2.15.0-py2.7.egg/boto/cloudfront/__init__.py", line 122, in _set_config
    raise CloudFrontServerError(response.status, response.reason, body)
boto.cloudfront.exception.CloudFrontServerError: CloudFrontServerError: 400 Bad Request
<?xml version="1.0"?>
<ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2010-11-01/"><Error><Type>Sender</Type><Code>IllegalUpdate</Code><Message>You cannot update the specified distribution using this API version.</Message></Error><RequestId>1400a8e8-45ed-11e3-95e4-3f1c6bfa28b9</RequestId></ErrorResponse>
```

**Comment by marksweb** [comment]
What's the status on the API support? I've got CloudFront serving static files & have been looking at how I might create an admin feature or deployment method to invalidate the CloudFront caches.

If there wasn't the latest API support 2 years ago, where does boto stand now? Has this been left open after support has been integrated?
