### ISSUE TITLE
Fixes UnicodeDecodeError raised when you 'vault.resume_archive_from_file'

### ISSUE THREAD

**Issue by JinnLynn** [boto/boto#2209]
I get this exception when I try to resume upload archive:

```
Traceback (most recent call last):
  File "t.py", line 36, in <module>
    filename=filepath
  File "/Users/JinnLynn/.virtualenvs/boto/lib/python2.7/site-packages/boto/glacier/vault.py", line 237, in resume_archive_from_file
    self, upload_id, part_size, file_obj, part_hash_map)
  File "/Users/JinnLynn/.virtualenvs/boto/lib/python2.7/site-packages/boto/glacier/writer.py", line 198, in resume_file_upload
    uploader.upload_part(part_index, part_data)
  File "/Users/JinnLynn/.virtualenvs/boto/lib/python2.7/site-packages/boto/glacier/writer.py", line 129, in upload_part
    content_range, part_data)
  File "/Users/JinnLynn/.virtualenvs/boto/lib/python2.7/site-packages/boto/glacier/layer1.py", line 1278, in upload_part
    response_headers=response_headers)
  File "/Users/JinnLynn/.virtualenvs/boto/lib/python2.7/site-packages/boto/glacier/layer1.py", line 113, in make_request
    data=data)
  File "/Users/JinnLynn/.virtualenvs/boto/lib/python2.7/site-packages/boto/connection.py", line 1046, in make_request
    retry_handler=retry_handler)
  File "/Users/JinnLynn/.virtualenvs/boto/lib/python2.7/site-packages/boto/connection.py", line 922, in _mexe
    request.body, request.headers)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 827, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf4 in position 0: ordinal not in range(128)
```

**Comment by jre** [comment]
The culprit seems to be commit a4c9a781f47a61ddde2b3a3802b93c1ed29cdf16 which unconditionally encodes all data read as utf-8. From what I can see: in python 2.x resuming upload of binary files is broken; in python 3.x resuming upload of any file by filename or by file object opened 'rb' is also broken.

It does not seem that boto is very well tested, nor that changes are very well reviewed.

**Comment by ddoskind** [comment]
FWIW, in my case this error was triggered by the fact that `boto` sets `unicode` headers,
but the message body is `str`, which results in `_send_output` failing when it tries to
assemble the message for the request.

I got rid of this behavior by providing my own `https_connection_factory`:

```python
from boto.https_connection import CertValidatingHTTPSConnection

# From `boto.connection.AWSAuthConnection`
http_exceptions = (boto_http_client.HTTPException, socket.error,
                   socket.gaierror, boto_http_client.BadStatusLine)


class PatchedHTTPSConnection(CertValidatingHTTPSConnection):

    # Override the constructor in order to enable SSL cert checking
    def __init__(self, *args, **kwargs):
        boto.https_connection.CertValidatingHTTPSConnection.__init__(self, *args, **kwargs)
        self.ca_certs = boto.connection.DEFAULT_CA_CERTS_FILE

    @staticmethod
    def _enc(string):
        if isinstance(string, unicode):
            return string.encode('utf-8')
        else:
            return string

    # We need to override `request()` or we'll get UnicodeDecodeErrors as boto provides
    # unicode headers, but the body can be bytes/str (when using Glacier, for example).
    def request(self, method, url, body=None, headers=None):
        """Send a complete request to the server."""
        actual_headers = {}
        if headers is not None:
            actual_headers = {self._enc(key): self._enc(value)
                              for key, value in headers.iteritems()}

        method = self._enc(method)
        url = self._enc(url)
        self._send_request(method, url, body, actual_headers)
````

then you can instantiate a new Glacier object like so:

````python
from boto.glacier.layer2 import Layer2


glacier = Layer2(aws_access_key_id=foo
                 aws_secret_access_key=bar,
                 https_connection_factory=(PatchedHTTPSConnection, http_exceptions)
````

With this approach, I no longer get `UnicodeDecodeErrors`.

The proper fix would probably be to patch `httplib` or have `boto` always use `str` or `bytes` when sending data.

**Comment by jinm** [comment]
Still seeing this issue with boto 2.38.0 and Python 2.7.3. Is there any newer official release to address this issue? Thanks.
