### ISSUE TITLE
boto.manage.task no longer works

### ISSUE THREAD

**Issue by kopertop** [boto/boto#2506]
As of boto version 2.32, boto.manage.task no longer can be imported:

```
Python 2.7.6 (default, Jul 24 2014, 12:53:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto
>>> boto.__version__
'2.32.1'
>>> import boto.manage.task
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "boto/manage/task.py", line 25, in <module>
    from boto.sdb.db.model import Model
  File "boto/sdb/db/model.py", line 60, in <module>
    class Model(object):
  File "boto/sdb/db/model.py", line 42, in __init__
    base.__sub_classes__.append(cls)
AttributeError: type object 'object' has no attribute '__sub_classes__'
>>> 
```

I suggest either fixing boto.sdb.db.model, or removing it entirely.

**Comment by sdobz** [comment]
I am also getting this, though only when testing in pycharm, boto==2.38.0

**Comment by unixnut** [comment]
I'm getting this same error when using boto boto-2.49.0 under Python 2.7.
