### ISSUE TITLE
s3put failing with --host

### ISSUE THREAD

**Issue by luxocrates** [boto/boto#2522]
I'm failing to get s3put working with a non-Amazon host. The command seems to fail automatically, without regard to what the host is. Am I using --host wrong?

I'm running a command with the pattern:

`% s3put --host whatever -b whatever -p $PWD $PWD/whatever`

and seeing this every time:

```
Traceback (most recent call last):
  File "/usr/local/bin/s3put", line 5, in <module>
    pkg_resources.run_script('boto==2.32.1', 's3put')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 489, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1207, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/boto-2.32.1-py2.7.egg/EGG-INFO/scripts/s3put", line 438, in <module>
    main()
  File "/Library/Python/2.7/site-packages/boto-2.32.1-py2.7.egg/EGG-INFO/scripts/s3put", line 347, in main
    c = boto.s3.connect_to_region(region or DEFAULT_REGION, **connect_args)
  File "/Library/Python/2.7/site-packages/boto-2.32.1-py2.7.egg/boto/s3/__init__.py", line 63, in connect_to_region
    return region.connect(**kw_params)
  File "/Library/Python/2.7/site-packages/boto-2.32.1-py2.7.egg/boto/s3/__init__.py", line 42, in connect
    return self.connection_cls(host=self.endpoint, **kw_params)
TypeError: type object got multiple values for keyword argument 'host'
```

The same command, executed without `--host whatever`, would upload successfully. Further, if I even use a `--host` like s3-us-west-1.amazonaws.com, it still fails in the same way.

**Comment by Captainkrtek** [comment]
This can be closed now since #2736 was merged
