### ISSUE TITLE
Keyring support for profiles not working

### ISSUE THREAD

**Issue by pmbapat** [boto/boto#2534]
If the ~/.boto file has multiple entries (different aws accounts), the keyring feature does not work for entries with [profile <name>]. It works only for the default fall back [Credentials] entry. 

Below is the error;

```
Traceback (most recent call last):
  File "testKeyring.py", line 6, in <module>
    conn = IAMConnection(profile_name="opsre")
  File "/Users/prashant/PMB/pyVirt/boto/lib/python2.7/site-packages/boto/iam/connection.py", line 73, in __init__
    profile_name=profile_name)
  File "/Users/prashant/PMB/pyVirt/boto/lib/python2.7/site-packages/boto/connection.py", line 1080, in __init__
    profile_name=profile_name)
  File "/Users/prashant/PMB/pyVirt/boto/lib/python2.7/site-packages/boto/connection.py", line 554, in __init__
    profile_name)
  File "/Users/prashant/PMB/pyVirt/boto/lib/python2.7/site-packages/boto/provider.py", line 198, in __init__
    self.get_credentials(access_key, secret_key, security_token, profile_name)
  File "/Users/prashant/PMB/pyVirt/boto/lib/python2.7/site-packages/boto/provider.py", line 294, in get_credentials
    profile_name)
boto.provider.ProfileNotFoundError: Profile "opsre" not found!
```

**Comment by sruggier** [comment]
I just encountered this today.

**Comment by lloydhazlett** [comment]
Still an issue with 2.38, suggested patch does fix.

**Comment by sachingharge** [comment]
Hi,

Can you please share provider.py with patch fix if possible?
I am getting syntax errors after applying patch fix in provider.py.

Thanks!

**Comment by sachingharge** [comment]
Hi again,

I am getting below error still after adding patch code in provider.py.
Please let me know your inputs on this, thanks!
-------------------------------------------------------------------------------------------------------------------------------------
File "update_ami_asg.py", line 61, in <module>
    "aws_access_key_id"], aws_secret_access_key=params["aws_secret_access_key"], profile_name=params['profile_name'])
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/__init__.py", line 66, in connect_to_region
    return region.connect(**kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto/regioninfo.py", line 187, in connect
    return self.connection_cls(region=self, **kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 103, in __init__
    profile_name=profile_name)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 555, in __init__
    profile_name)
  File "/usr/local/lib/python2.7/site-packages/boto/provider.py", line 200, in __init__
    self.get_credentials(access_key, secret_key, security_token, profile_name)
  File "/usr/local/lib/python2.7/site-packages/boto/provider.py", line 296, in get_credentials
    profile_name)
-------------------------------------------------------------------------------------------------------------------------------------

**Comment by jamesongithub** [comment]
still not fixed...

**Comment by mwgamble** [comment]
@jamesongithub I've submitted a pull request to the `botocore` library that adds support for the keyring: https://github.com/boto/botocore/pull/1262. We'd appreciate it if you voiced your support for the functionality there - it might help get it accepted sooner.

**Comment by jamesongithub** [comment]
ok @mwgamble
