### ISSUE TITLE
UnboundLocalError: local variable 'e' referenced before assignment

### ISSUE THREAD

**Issue by tarekziade** [boto/boto#2595]
Looks like 'e' is not defined when I reach that line...

``` python
======================================================================
ERROR: test_create_instance (loadsbroker.tests.test_awsctrl.TestAWSCtrl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tarek/Dev/github.com/loads-broker/lib/python3.4/site-packages/moto/core/models.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "/Users/tarek/Dev/github.com/loads-broker/loadsbroker/tests/test_awsctrl.py", line 26, in test_create_instance
    image = conn.get_all_images(image_ids=[ami])[0]
  File "/Users/tarek/Dev/github.com/loads-broker/lib/python3.4/site-packages/boto-2.32.1-py3.4.egg/boto/ec2/connection.py", line 190, in get_all_images
    [('item', Image)], verb='POST')
  File "/Users/tarek/Dev/github.com/loads-broker/lib/python3.4/site-packages/boto-2.32.1-py3.4.egg/boto/connection.py", line 1150, in get_list
    response = self.make_request(action, params, path, verb)
  File "/Users/tarek/Dev/github.com/loads-broker/lib/python3.4/site-packages/boto-2.32.1-py3.4.egg/boto/connection.py", line 1096, in make_request
    return self._mexe(http_request)
  File "/Users/tarek/Dev/github.com/loads-broker/lib/python3.4/site-packages/boto-2.32.1-py3.4.egg/boto/connection.py", line 1010, in _mexe
    elif e:
UnboundLocalError: local variable 'e' referenced before assignment
```

**Comment by Aameer** [comment]
```
[servername]$ python3.4 manage.py shell
Python 3.4.1 (default, Oct  7 2014, 18:12:51)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from misc_scripts.crons.dropbox_integrate import get_bucket
>>> bucket = get_bucket()
 S3 connection successful
>>> k=bucket.new_key('3615/video/3615_20.mkv')
>>> k.set_contents_from_filename('3910.mkv')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/path_to_lib/lib/boto/s3/key.py", line 1357, in set_contents_from_filename
    encrypt_key=encrypt_key)
  File "/path_to_lib/indeev5/lib/boto/s3/key.py", line 1288, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/path_to_lib/lib/boto/s3/key.py", line 748, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/path_to_lib/lib/boto/s3/key.py", line 946, in _send_file_internal
    query_args=query_args
  File "/path_to_lib/lib/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/path_to_lib/lib/boto/connection.py", line 1067, in make_request
    retry_handler=retry_handler)
  File "/path_to_lib/lib/boto/connection.py", line 1025, in _mexe
    elif e:
UnboundLocalError: local variable 'e' referenced before assignment
```
I am using boto 2.37.0

I think this is the same issue as mentioned here (https://github.com/boto/boto/issues/2595)

will the upgrade to 2.38.0 resolve this issue

thanks
