### ISSUE TITLE
Glacier uploads are broken on python2

### ISSUE THREAD

**Issue by adq** [boto/boto#2603]
Hi, if I try and upload a *large binary* file to glacier (ie one which needs multipart) with boto, it fails with a UnicodeDecodeError. It works fine with small files (ie non-multiparters).

I've figured out why, but first here is my code and the error message:

My code:
```
glacierConn = boto.glacier.connect_to_region("eu-west-1",
                                             aws_access_key_id=ACCESS,
                                             aws_secret_access_key=SECRET)
vault = glacierConn.get_vault("myvault")
archiveId = vault.upload_archive("/tmp/test", description="test")
```

Error message:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/adq/dev/tvsquared-backend/tvsquared/tmp/adq/gtest.py", line 11, in <module>
    archiveId = vault.upload_archive("/tmp/test", description="test")
  File "/usr/lib/python2.7/site-packages/boto/glacier/vault.py", line 87, in upload_archive
    return self.create_archive_from_file(filename, description=description)
  File "/usr/lib/python2.7/site-packages/boto/glacier/vault.py", line 177, in create_archive_from_file
    writer.write(data)
  File "/usr/lib/python2.7/site-packages/boto/glacier/writer.py", line 219, in write
    self.partitioner.write(data)
  File "/usr/lib/python2.7/site-packages/boto/glacier/writer.py", line 61, in write
    self._send_part()
  File "/usr/lib/python2.7/site-packages/boto/glacier/writer.py", line 75, in _send_part
    self.send_fn(part)
  File "/usr/lib/python2.7/site-packages/boto/glacier/writer.py", line 222, in _upload_part
    self.uploader.upload_part(self.next_part_index, part_data)
  File "/usr/lib/python2.7/site-packages/boto/glacier/writer.py", line 129, in upload_part
    content_range, part_data)
  File "/usr/lib/python2.7/site-packages/boto/glacier/layer1.py", line 1279, in upload_part
    response_headers=response_headers)
  File "/usr/lib/python2.7/site-packages/boto/glacier/layer1.py", line 114, in make_request
    data=data)
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1053, in make_request
    retry_handler=retry_handler)
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 926, in _mexe
    request.body, request.headers)
  File "/usr/lib/python2.7/httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 842, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 86: ordinal not in range(128)
```

I am passing non-unicode strs into boto. The problem is caused during the get_vault() call: it connects to the API, and retrieves the vault details, including the vault name, as unicode strings.

When I later call upload_archive(), httplib ends up being passed the vault name as a unicode string, which causes it to try and interpret my binary file as a unicode string (which fails, surprise!)

As a quick bodge, if I forcibly convert the vault name back to unicode, it works fine again:
```
glacierConn = boto.glacier.connect_to_region("eu-west-1",
                                             aws_access_key_id=ACCESS,
                                             aws_secret_access_key=SECRET)
vault = glacierConn.get_vault("myvault")
vault.name = str(vault.name)
archiveId = vault.upload_archive("/tmp/test", description="test")
```

This problem started a month or so ago, I suspect some of the python3 changes have broken it.

I'm using boto 2.32.1, python 2.7.8 on Arch Linux (x64).

**Comment by slashrsm** [comment]
I am still seeing this with 2.36.0

**Comment by dchang0** [comment]
Confirmed that felixonmars' patch "glacier: forcing vault_name to be str, fixes #2603" fixes the problem with boto 2.36.0 on Ubuntu 12.04.5 LTS with python 2.7.3. Thanks felixonmars!

**Comment by anttivs** [comment]
Seeing this with boto 2.38.0 with Python 2.7.9 on Mac OS X 10.8.5, the patch mentioned above resolves the problem.

**Comment by aspiers** [comment]
Same here for me with boto 2.34.0 and Python 2.7.6 on openSUSE 13.1.

**Comment by swordeh** [comment]
+1 

Experiencing this issue with 2.38.0, OS X 10.10.2 and Python 2.7.6. I've downgraded to 2.31.1 as mentioned by @catlee and my uploaded worked fine.

**Comment by edi9999** [comment]
It would be great to have a fix for this !
