### ISSUE TITLE
Boto config file parsing error

### ISSUE THREAD

**Issue by tarekziade** [boto/boto#2617]
Bug on Python 3.4 if I set the is_secure flag in [Boto]

```
Traceback (most recent call last):
 [...]
  File "/Users/tarek/Dev/github.com/loads-broker/lib/python3.4/site-packages/boto-2.32.1-py3.4.egg/boto/ec2/__init__.py", line 66, in connect_to_region
    return region.connect(**kw_params)
  File "/Users/tarek/Dev/github.com/loads-broker/lib/python3.4/site-packages/boto-2.32.1-py3.4.egg/boto/regioninfo.py", line 187, in connect
    return self.connection_cls(region=self, **kw_params)
  File "/Users/tarek/Dev/github.com/loads-broker/lib/python3.4/site-packages/boto-2.32.1-py3.4.egg/boto/ec2/connection.py", line 103, in __init__
    profile_name=profile_name)
  File "/Users/tarek/Dev/github.com/loads-broker/lib/python3.4/site-packages/boto-2.32.1-py3.4.egg/boto/connection.py", line 1081, in __init__
    profile_name=profile_name)
  File "/Users/tarek/Dev/github.com/loads-broker/lib/python3.4/site-packages/boto-2.32.1-py3.4.egg/boto/connection.py", line 478, in __init__
    is_secure = config.getboolean('Boto', 'is_secure')
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/configparser.py", line 798, in getboolean
    def getboolean(self, section, option, *, raw=False, vars=None,
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/configparser.py", line 776, in _get
    return conv(self.get(section, option, **kwargs))
TypeError: get() got an unexpected keyword argument 'raw'
```

**Comment by tarekziade** [comment]
Ok so here's what I have to do until it gets fixed

```python
try:
    from boto.pyami.config import Config, ConfigParser

    def get(self, section, name, default=None, **kw):
        try:
            val = ConfigParser.get(self, section, name, **kw)
        except:
            val = default
        return val

    Config.get = get

except ImportError:
    pass
```

**Comment by tarekziade** [comment]
poke @alfredodeza :)

**Comment by jseabold** [comment]
This is all a bit silly. There are still a lot of projects out there that use `boto` and the blanket try/except swallowing a real error here makes this pretty hard to track down.

**Comment by jamesls** [comment]
I believe this is fixed via https://github.com/boto/boto/issues/3474, but is not available in the boto release yet.  Let me double check the boolean case is fixed as well.

**Comment by jseabold** [comment]
@jamesls That would be great.

**Comment by jamesls** [comment]
Confirmed fixed in python3 with the pull requested mentioned above.  This will be available in the next boto release.
