### ISSUE TITLE
get_all_security_groups does not grab sg from non-default VPC when using groupnames

### ISSUE THREAD

**Issue by miliauskaite** [boto/boto#2651]
get_all_security_groups() does not grab security group from non-default VPC when specifying the list of groupnames

To demonstrate:
- call `get_all_security_groups()`, returns all security groups from all VPCs correctly
- call `get_all_security_groups(groupnames=["sg_in_default_VPC"])`, works correctly
- call `get_all_security_groups(groupnames=["sg_in_non-default_VPC"])`, fails with 

Traceback (most recent call last):
`File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/boto/ec2/connection.py", line 2970, in get_all_security_groups
    [('item', SecurityGroup)], verb='POST')
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 1169, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'sg_in_non-default_VPC' does not exist in default VPC '<my_default_vpc>'</Message></Error>`</Errors>...

Even if I add specific vpc filter:
`get_all_security_groups(groupnames=["sg_in_non-default_VPC"], filters={"vpc-id: <my_nondefault_vpc_id>"} )`
fails with the same error

```
* Python : 2.7 
* boto: 2.32.0
```

**Comment by mattmb** [comment]
Seeing the same thing. Looks like get_all_security_groups only finds SGs in the default VPC...

**Comment by mattmb** [comment]
Looks like this is a [limit](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSecurityGroups.html) of the EC2 api:
```
    def get_sg(self, name, vpc_id=None):
        if vpc_id:
            f = {'group-name':name,'vpc-id':vpc_id}
            groups = self.conn_ec2.get_all_security_groups(filters=f)
        else:
            groups = self.conn_ec2.get_all_security_groups(groupnames=[name])
        return groups[0] if groups else None
```
seems to work for me

**Comment by hannes-ucsc** [comment]
@mattmb's workaround works for me, too.
