### ISSUE TITLE
No attributes are returned in SQS message

### ISSUE THREAD

**Issue by gongchengshi** [boto/boto#2699]
>>> boto.__version__
'2.33.0'
>>> message = queue.read(message_attributes=['.*'])
>>> message.attributes
{}
>>> message.message_attributes
{}
>>> sent = message.attributes['SentTimestamp']
Traceback (most recent call last):
  File "/opt/pycharm-3.4.1/helpers/pydev/pydevd_exec.py", line 3, in Exec
    exec exp in global_vars, local_vars
  File "<input>", line 1, in <module>
KeyError: 'SentTimestamp'

There is also an unanswered question about this on Stackoverflow: http://stackoverflow.com/questions/14945604/sqs-how-can-i-read-the-sent-time-of-an-sqs-message-using-pythons-boto-library

**Comment by cancan101** [comment]
I think the bug is here: https://github.com/boto/boto/blob/90a5d4485163ebd82f4e6e107c60b0263a468046/boto/sqs/queue.py#L208

**Comment by Bustead** [comment]
@gongchengshi is this still relevant? Any chance this resolved is resolved by using Boto3?
