### ISSUE TITLE
Can not create TCP health check

### ISSUE THREAD

**Issue by toote** [boto/boto#2721]
At this time it is impossible to create a TCP health check because the XML template forces the inclusion of the `<ResourcePath>` element:

```
>>> hc = HealthCheck('', port, 'TCP', None, 'test.example.com')
>>> conn.create_health_check(hc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../lib/python2.7/site-packages/boto/route53/connection.py", line 276, in create_health_check
    raise exception.DNSServerError(response.status, response.reason, body)
boto.route53.exception.DNSServerError: DNSServerError: 400 Bad Request
<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidInput</Code><Message>TCP health checks must not have a resource path specificed.</Message></Error><RequestId>XXXXX</RequestId></ErrorResponse>
```

**Comment by ficusyou** [comment]
Is there any update on this bug, I've also been unable to create TCP health checks using boto.
