### ISSUE TITLE
S3 bucket lookup / get_bucket broken for eu-central-1 (Frankfurt)

### ISSUE THREAD

**Issue by wibou7** [boto/boto#2741]
This bug might be caused by a bug in AWS but just in case it is not (or that their is a work around).
Test setup:
boto 2.34.0
python 2.6.6
CentOS 6.5
### Step to reproduce

1 - Create 2 buckets on S3. I've done this using the web interface, but it shouldn't matter.
One must be in Frankfurt (eu-central-1) (here: "56885685-test-bucket-in-frankfurt")
One in another region, e.g. US Standard (us-east-1) (here: "56885685-test-bucket-in-north-virginia")
(you can pick any other region here, I tested with Ireland as well it the same behavior would occur)

2- List all buckets. They would both show:

``` python
from boto.s3.connection import S3Connection
conn = S3Connection(AMAZON_ACCESS_KEY, AMAZON_SECRET_KEY) # Replace with your creds
allBuckets = conn.get_all_buckets()
for bucket in allBuckets:
   print(str(bucket.name))
```

Result:
56885685-test-bucket-in-frankfurt
56885685-test-bucket-in-north-virginia

3- Try to get each bucket individually:

``` python
from boto.s3.connection import S3Connection
conn = S3Connection(AMAZON_ACCESS_KEY, AMAZON_SECRET_KEY) # Replace with your creds
bucketName = "56885685-test-bucket-in-north-virginia"
bucketName2 = "56885685-test-bucket-in-frankfurt"
bucket1 = conn.lookup(bucketName)
print("North Virginia Bucket: " + str(bucket1))
bucket2 = conn.lookup(bucketName2)
print("Frankfurt Bucket: " + str(bucket2))
```

Result:
`North Virginia Bucket: <Bucket: 56885685-test-bucket-in-north-virginia>`
`Frankfurt Bucket: None`
### Investigation

Upon ivestigation, I believe this might actually be caused by a bug on AWS side, but I still have a doubt.
In the file: "boto/s3/connection.py" at line 522, I added:
`print("* STATUS: " + str(response.status))`

Now executing the code above give me
North Virginia:
`* STATUS: 200`
Frankfurt:
`* STATUS: 400`

Thuis might (???) be caused by internal stuff in boto, but it is more likely to be the direct HTTP answer returned by the rest call to AWS... so their own support for Frankfurt may be broken.

**Comment by synotna** [comment]
Ditto. Are there any plans for a better workaround for this? e.g. so that libs that depend on boto (django-storages, -redux) do not have to make changes? e.g. add an S3_FRANKFURT_WORKAROUND :)

I just switched to Ireland instead

**Comment by synotna** [comment]
And Ireland is affected now too. Is the solution move everything to us-east-1 and hope Amazon does something before rolling out there? Or is there anything boto can do in the mean time, e.g. try v4 first, then fall back to v2?

**Comment by wibou7** [comment]
@synotna 
Cannot reproduce with Ireland (thanks gosh), how is it affected synota?  Please post repro steps.

**Comment by synotna** [comment]
Ireland seems to be usable for me again - though still with ResourceWarning unclosed socket messages after every action, with or without SSL enabled

Not sure if I had a config hiccup while testing different regions or Ireland went funny for a while

**Comment by yoav-steinberg** [comment]
Looking at how the s3cmd overcomes the issue of figuring out where a bucket is located before actually accessing it I found the following s3 feature: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html

This can enable us to query where the bucket is located and then set the host accordingly. I'd suggest adding this somehow to the get_bucket/get_all_buckets API's.

**Comment by yeonsh** [comment]
@yoav-steinberg We can't get location information from S3 Frankfurt region because that region requires AWS Signature V4 and V4 needs region to make signature. 

If we send a request to S3 Frankfurt with AWS Signature V2 which works without region information, it returns:

```<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>57FB9804331CD10B</RequestId><HostId>YPLHc36mDPKEWy+/hjGImnVQ2jZIxOd8eiPq+7uz2bQW18JSmqZ+6fDHIkxYzAYBGsd3siV6xDw=</HostId></Error>```

Anyone knows how to get region information for these regions without AWS Signature V4? (China and Frankfurt).

**Comment by pikeas** [comment]
Any movement on this?

**Comment by eahefnawy** [comment]
I changed to the Ireland bucket just for this issue -_-

**Comment by joephein** [comment]
Same for me, moving to Ireland region solved issues with trovebox / openphoto.

**Comment by eproxus** [comment]
What's the status on this?

**Comment by ManuelB** [comment]
Just to let you know I currently hit this bug when trying to backup my ubuntu 14.04 laptop using Backup which is the ubuntu name of Deja Dup which uses duplicity which uses boto for connecting to the S3 buchet in Frankfurt:

```
/usr/bin/duplicity collection-status --include=/home/manuel/.cache/deja-dup/metadata --exclude=/home/manuel/.local/share/Trash --exclude=/home/manuel/.xsession-errors --exclude=/home/manuel/.thumbnails --exclude=/home/manuel/.cache/deja-dup --exclude=/home/manuel/.cache --include=/home/manuel --exclude=/sys --exclude=/run --exclude=/proc --exclude=/var/tmp --exclude=/tmp --exclude=** --s3-use-new-style s3+http://manuel-backup-xps-13/manuel-backup-xps-13 --no-encryption --verbosity=9 --gpg-options=--no-use-agent --archive-dir=/home/manuel/.cache/deja-dup --tempdir=/tmp --s3-european-buckets
Using archive dir: /home/manuel/.cache/deja-dup/b6b05540446d14a3219898ba11eec321
Using backup name: b6b05540446d14a3219898ba11eec321
Import of duplicity.backends.azurebackend Succeeded
Import of duplicity.backends.botobackend Succeeded
Import of duplicity.backends.cfbackend Succeeded
Import of duplicity.backends.copycombackend Succeeded
Import of duplicity.backends.dpbxbackend Succeeded
Import of duplicity.backends.gdocsbackend Succeeded
Import of duplicity.backends.giobackend Succeeded
Import of duplicity.backends.hsibackend Succeeded
Import of duplicity.backends.hubicbackend Succeeded
Import of duplicity.backends.imapbackend Succeeded
Import of duplicity.backends.lftpbackend Succeeded
Import of duplicity.backends.localbackend Succeeded
Import of duplicity.backends.megabackend Succeeded
Import of duplicity.backends.multibackend Succeeded
Import of duplicity.backends.ncftpbackend Succeeded
Import of duplicity.backends.onedrivebackend Succeeded
Import of duplicity.backends.par2backend Succeeded
Import of duplicity.backends.pydrivebackend Succeeded
Import of duplicity.backends.rsyncbackend Succeeded
Import of duplicity.backends.ssh_paramiko_backend Succeeded
Import of duplicity.backends.ssh_pexpect_backend Succeeded
Import of duplicity.backends.swiftbackend Succeeded
Import of duplicity.backends.sxbackend Succeeded
Import of duplicity.backends.tahoebackend Succeeded
Import of duplicity.backends.webdavbackend Succeeded
Using temporary directory /tmp/duplicity-Mtf4fy-tempdir
Backend error detail: Traceback (most recent call last):
  File "/usr/bin/duplicity", line 1523, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 1517, in with_tempdir
    fn()
  File "/usr/bin/duplicity", line 1355, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1093, in ProcessCommandLine
    globals.backend = backend.get_backend(args[0])
  File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/lib/python2.7/dist-packages/duplicity/backends/_boto_single.py", line 161, in __init__
    self.resetConnection()
  File "/usr/lib/python2.7/dist-packages/duplicity/backends/_boto_single.py", line 187, in resetConnection
    raise BackendException(err.message)
BackendException

BackendException:
```

When changing 'BackendException(err.message)' to 'BackendException(err)'. I get:

BackendException: S3ResponseError: 400 Bad Request

**Comment by ManuelB** [comment]
$ sudo pip show boto
---
Name: boto
Version: 2.38.0
Location: /usr/local/lib/python2.7/dist-packages
Requires:

This bug is mentioned here as well:
https://bugs.launchpad.net/duplicity/+bug/1407966

**Comment by ideallical** [comment]
same here. moved to Ireland in the meanwhile.

**Comment by CVirus** [comment]
Any hope on this one ?

**Comment by art-eltyshev** [comment]
with `validate=False` parameter in `get_bucket` works good (python3)

```python
import boto

boto.config.load_from_path('.boto')
conn = boto.connect_s3()
bucket = conn.get_bucket('some-test-bucket', validate=False)
print(bucket.list())
```

From boto [docs](http://boto.readthedocs.org/en/latest/s3_tut.html#accessing-a-bucket)

> Warning
If validate=False is passed, no request is made to the service (no charge/communication delay). This is only safe to do if you are sure the bucket exists.
If the default validate=True is passed, a request is made to the service to ensure the bucket exists. Prior to Boto v2.25.0, this fetched a list of keys (but with a max limit set to 0, always returning an empty list) in the bucket (& included better error messages), at an increased expense. As of Boto v2.25.0, this now performs a HEAD request (less expensive but worse error messages).

In this case boto doesn't make that failing HEAD request.

**Comment by toastdriven** [comment]
The root cause on this is likely https://github.com/boto/boto/blob/321f6dc519ee72b3cfeba43a371f9736e29f0492/boto/auth.py#L914-L915, which only adds SigV4 signing for the China regions. `eu-central-1` seems to require this signing (- "This new Region supports only Signature Version 4"), so updating that line should be all that is needed.

**Comment by yoav-steinberg** [comment]
Here's my workaround for a generic (region safe) get_bucket, hope this helps someone:
```python
import xml.etree.ElementTree as ET

def get_bucket(aws_key, aws_secret, bucketname):
    conn = S3Connection(aws_key, aws_secret, host='s3.amazonaws.com')
    bucket = conn.get_bucket(bucketname, validate=False)
    # Read bucket location, just to make sure we have access to this region
    try:
        bucket.get_location()
    except S3ResponseError as e:
        if e.status == 400 and e.error_code == 'AuthorizationHeaderMalformed':
            conn.auth_region_name = ET.fromstring(e.body).find('./Region').text # Fix conn's region in case it was wrong
    return conn.get_bucket(bucketname) # get the bucket again, this time with validation
```

And don't for get adding the following to boto.cfg:
```ini
[s3]
use-sigv4 = True
```

**Comment by asteinlein** [comment]
Just hit by this as well – we're unable to use our Frankfurt bucket. Please try to resolve this in a release soon.

**Comment by rosscdh** [comment]
+1 big problem

**Comment by lukasklein** [comment]
+1

**Comment by kopax** [comment]
Have the same problem +1

**Comment by gulbinas** [comment]
+1 Frankfurt bucket also

**Comment by stejy** [comment]
I'm now getting this issue on Ireland now as well. It was working a couple of days ago.

**Comment by maliklalani** [comment]
any update on this? Getting same issue for all buckets in Frankfurt.

**Comment by lsde** [comment]
+1

**Comment by jdn-za** [comment]
+1

**Comment by phyber** [comment]
Just started hitting this issue. Fixed it locally by removing the `self.head_bucket` call from `get_bucket` in `s3/connection.py`.
In my case, boto was being called by `duplicity`.

**Comment by phyber** [comment]
After poking around some more, this issue was caused by an incorrect IAM policy for me.

Although I already had policies to allow `s3:ListBucket` (working fine for `s3cmd` and Duplicati), they were policies with `Conditions` on the `s3:prefix` and `s3:delimiter`.
It seems that with the `boto` `HEAD` request, those ACLs weren't good enough and I had to simply add a plain `s3:ListBucket` ACL for that specific bucket without any condition on the `s3:prefix` or `s3:delimiter`.

**Comment by muhammad-ammar** [comment]
Just hit with this same issue. +1

**Comment by freeyoung** [comment]
the same issue here. +1.

**Comment by chhantyal** [comment]
This issue is open since 2014. S3 Frankfurt region is completely unusable because of this issue. How are people still paying and using AWS?

**Comment by navidkhn1** [comment]
Stuck with the same issue at Mumbai. Needs to be solved!

**Comment by VinQbator** [comment]
+1

**Comment by martin3000** [comment]
You can try to create a file ~/.boto and put in the following:

[s3]
host=s3.eu-central-1.amazonaws.com

(of course adapt host name for mumbai)

Martin Schlatter

**Comment by jpabbuehl** [comment]
same issue here,
martin3000's suggestion solved this problem.
thx

**Comment by zubairalam** [comment]
@martin3000 solution works.
for `Mumbai` region, config would be 
[s3]
host=s3.ap-south-1.amazonaws.com

to know how a boto config works [http://boto.cloudhackers.com/en/latest/boto_config_tut.html](url)

**Comment by rajasaurus** [comment]
~/.boto nor ~/.aws/.boto fix didn't work for me..  since i had awscli installed i tried this and it ended up working:

error: botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the ListObjectsV2 operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

% aws configure set default.s3.signature_version s3v4

this updates /.aws/config with:

s3 = signature_version = s3v4

reference: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html

**Comment by oesah** [comment]
I have the same Issue with Frankfurt... The problem for me only occurs, when I login to Django. If I am logged out, no problem at all! Tried everything suggested here.

I can't believe that they didn't fix this issue yet, since it seems to be a huge one. Without S3 in Frankfurt, it does not make sense for us to us S3 at all..

**Comment by martin3000** [comment]
oesah what same issue?
I had to change /usr/lib/python2.7/dist-packages/boto/s3/connection.py because there was a problem with the default host.

**Comment by oesah** [comment]
hmmmmmm, I have no idea what I did, but it works now. I tried all of the suggestions above, but it didn't help. I don't know why, but now it seems to work.

It would be good, if this issue is solved generically though, because it's a no go for production. My solution is to create a custom storages:

```
# custom_storages.py
import os

from django.conf import settings
from storages.backends.s3boto import S3BotoStorage

os.environ['S3_USE_SIGV4'] = 'True'

class MediaStorage(S3BotoStorage):
    location = settings.MEDIAFILES_LOCATION

    @property
    def connection(self):
        if self._connection is None:
            self._connection = self.connection_class(
                self.access_key, self.secret_key,
                calling_format=self.calling_format, host='s3.eu-central-1.amazonaws.com')
        return self._connection
```

```
# settings.py
AWS_ACCESS_KEY_ID = env('DJANGO_AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('DJANGO_AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('DJANGO_AWS_STORAGE_BUCKET_NAME')
AWS_AUTO_CREATE_BUCKET = True
AWS_QUERYSTRING_AUTH = False
AWS_S3_CALLING_FORMAT = OrdinaryCallingFormat()

AWS_EXPIRY = 60 * 60 * 24 * 7

AWS_HEADERS = {
    'Cache-Control': six.b('max-age=%d, s-maxage=%d, must-revalidate' % (
        AWS_EXPIRY, AWS_EXPIRY))
}

AWS_S3_DOMAIN = 's3.amazonaws.com/%s' % AWS_STORAGE_BUCKET_NAME
MEDIAFILES_LOCATION = 'media'

MEDIA_URL = "https://%s/%s/" % (AWS_S3_DOMAIN, MEDIAFILES_LOCATION)
DEFAULT_FILE_STORAGE = 'config.settings.custom_storages.MediaStorage'
```

**Comment by mickeyperlstein** [comment]
Still an issue in 2016. only in Frankfurt, not in the US or anywhere else. just frankfurt. great work AWS.

**Comment by nehaljwani** [comment]
The workaround mentioned at https://github.com/jschneier/django-storages/issues/28#issuecomment-265876674 worked for me.

**Comment by amq** [comment]
2017
boto 2.45.0
duplicity 0.7.11
Frankfurt

Whatever I'd do, I'd get one of:

`When using SigV4, you must specify a 'host' parameter.`

`The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.`

`The EU location constraint is incompatible for the region specific endpoint this request was sent to.`

**Comment by jm66** [comment]
Same behaviour in Canada (Central)

**Comment by telepath** [comment]
For everyone still having this problem:

Please make sure that your ~/.aws/config contains the region FOR EACH PROFILE, e.g.

```
[profile default]
region = eu-central-1

[profile prod]
region = eu-central-1

[profile admin]
role_arn = arn:aws:iam::############:role/admin
source_profile = default
region = eu-central-1

[profile prod-admin]
role_arn = arn:aws:iam::############:role/admin
source_profile = prod
region = eu-central-1
```

**Comment by martin3000** [comment]
I changed connection.py because in my opinion the handling of DefaultHost ist wrong.
If there is not host provided, but when we have a DefaultHost, the original code sets the variable no_host_provided=true which does not make sense.

Old code:
`class S3Connection(AWSAuthConnection):

    DefaultHost = boto.config.get('s3', 'host', 's3.amazonaws.com')
    DefaultCallingFormat = boto.config.get('s3', 'calling_format', 'boto.s3.connection.SubdomainCallingFormat')
    QueryString = 'Signature=%s&Expires=%d&AWSAccessKeyId=%s'

    def __init__(self, aws_access_key_id=None, aws_secret_access_key=None,
                 is_secure=True, port=None, proxy=None, proxy_port=None,
                 proxy_user=None, proxy_pass=None,
                 host=NoHostProvided, debug=0, https_connection_factory=None,
                 calling_format=DefaultCallingFormat, path='/',
                 provider='aws', bucket_class=Bucket, security_token=None,
                 suppress_consec_slashes=True, anon=False,
                 validate_certs=None, profile_name=None):
        no_host_provided = False
        if host is NoHostProvided:
            no_host_provided = True
            host = self.DefaultHost
        if isinstance(calling_format, six.string_types):
            calling_format=boto.utils.find_class(calling_format)()
        self.calling_format = calling_format
        self.bucket_class = bucket_class
        self.anon = anon
        super(S3Connection, self).__init__(host,
                aws_access_key_id, aws_secret_access_key,
                is_secure, port, proxy, proxy_port, proxy_user, proxy_pass,
                debug=debug, https_connection_factory=https_connection_factory,
                path=path, provider=provider, security_token=security_token,
                suppress_consec_slashes=suppress_consec_slashes,
                validate_certs=validate_certs, profile_name=profile_name)
        # We need to delay until after the call to ``super`` before checking
        # to see if SigV4 is in use.
        if no_host_provided:
            if 'hmac-v4-s3' in self._required_auth_capability():
                raise HostRequiredError(
                    "When using SigV4, you must specify a 'host' parameter."
                )`

new code:
`class S3Connection(AWSAuthConnection):

    DefaultHost = boto.config.get('s3', 'host', 's3.amazonaws.com')
    DefaultCallingFormat = boto.config.get('s3', 'calling_format', 'boto.s3.connection.SubdomainCallingFormat')
    QueryString = 'Signature=%s&Expires=%d&AWSAccessKeyId=%s'

    def __init__(self, aws_access_key_id=None, aws_secret_access_key=None,
                 is_secure=True, port=None, proxy=None, proxy_port=None,
                 proxy_user=None, proxy_pass=None,
                 host=NoHostProvided, debug=0, https_connection_factory=None,
                 calling_format=DefaultCallingFormat, path='/',
                 provider='aws', bucket_class=Bucket, security_token=None,
                 suppress_consec_slashes=True, anon=False,
                 validate_certs=None, profile_name=None):
        no_host_provided = False
        #mod by jms:
        if host is NoHostProvided:
            if self.DefaultHost == '': no_host_provided = True
            else: host = self.DefaultHost
        if isinstance(calling_format, six.string_types):
            calling_format=boto.utils.find_class(calling_format)()
        self.calling_format = calling_format
        self.bucket_class = bucket_class
        self.anon = anon
        boto.log.debug('in s3/connection calling super, host='+host)
        super(S3Connection, self).__init__(host,
                aws_access_key_id, aws_secret_access_key,
                is_secure, port, proxy, proxy_port, proxy_user, proxy_pass,
                debug=debug, https_connection_factory=https_connection_factory,
                path=path, provider=provider, security_token=security_token,
                suppress_consec_slashes=suppress_consec_slashes,
                validate_certs=validate_certs, profile_name=profile_name)
        # We need to delay until after the call to ``super`` before checking
        # to see if SigV4 is in use.
        if no_host_provided:
            if 'hmac-v4-s3' in self._required_auth_capability():
                raise HostRequiredError(
                    "When using SigV4, you must specify a 'host' parameter."
                )`

**Comment by stonefury** [comment]
What is actually the REAL work-around for boto 2.48 to access S3 buckets that use V4? I see lots of suggestions, not sure what's the right one.

**Comment by telepath** [comment]
@stonefury make sure the call contains the region, either by including it with the call explicitly,  or by configuring it in the config.

**Comment by stonefury** [comment]
@telepath GOT IT. Thanks.  host=<full s3 dns from aws> worked for 2.48.

**Comment by oferzi23** [comment]
@stonefury could you give a clean explanation how you solved this?

**Comment by szeitlin** [comment]
same issue, +1. 

Tried validate=False, creating a .boto file, and adding the sig4 environment variable. So far none of that is working.

**Comment by stonefury** [comment]
It's been awhile, but I think this was all that was needed.

s3 = boto.connect_s3(host='s3.ca-central-1.amazonaws.com')

**Comment by szeitlin** [comment]
yes, this also works for s3fs, which uses boto3. I had to update to a newer version of boto3, that was part of the problem.

**Comment by cleverca22** [comment]
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

from the experiments ive done today trying to solve the same issue, attempting to create a bucket on a "version 4 only" region will taint the routing caches in AWS, and not allow re-using that bucket name in nixops again for an unknown period of time, a new bucket name must be tried, on a version that supports version 3

**Comment by rahul0090392** [comment]
conn = S3Connection(ACCESS_KEY,SECRET_KEY, calling_format=OrdinaryCallingFormat())
Just adding this line solved the issue

**Comment by rajneeshaggarwal** [comment]
Following code worked for me:

```
from boto.s3.connection import S3Connection
conn = S3Connection(aws_access_key, aws_secret_key, host='s3.us-east-2.amazonaws.com')
```

**Comment by vedmant** [comment]
I have the same issue, similar package 'aws-sdk' works just fine on node.js with no need to specify host.

**Comment by stormm2138** [comment]
boto2 working .boto config:

```bash
[s3]
use-sigv4 = True
host=s3.eu-central-1.amazonaws.com
```

**Comment by ghost** [comment]
Doesn't work for me. Like I said in #9376 I think that boto is ignoring configuration for some reasons I don't get.

**Comment by lucabezerra** [comment]
For anyone who arrives here and is not having Frankfurt-specific issues, what solved it for me was, on top of adding the `host` information, also changing the signature version to 4 before creating the connection, since this is not my main bucket and the main one uses a different sigVer:

``` python
import boto
from boto.s3.connection import S3Connection

use_sigv4 = boto.config.get('s3', 'use-sigv4')
if not use_sigv4: 
    boto.config.add_section('s3') 
    boto.config.set('s3', 'use-sigv4', 'True')

conn = S3Connection(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, host='s3.us-east-2.amazonaws.com')
bucket = conn.get_bucket(AWS_STORAGE_BUCKET_NAME)
# do your stuff

# restore the signature version, if it applies
if not use_sigv4:
    boto.config.remove_section('s3')
```

**Comment by trajano** [comment]
I think this is may be the same issue I am facing in `ap-east-1`

**Comment by ripley** [comment]
It's July 2020, still the same issue  -___-|||
