### ISSUE TITLE
Cannot download log file with binary data

### ISSUE THREAD

**Issue by Altonymous** [boto/boto#2748]
Here's the code:

```
import boto.rds
conn = boto.connect_rds()
with open('test.log', 'w') as f:
    for log_file in conn.get_all_logs('prd-access-logs-01', None):
        log = conn.get_log_file('prd-access-logs-01', log_file.log_filename)
        f.write(log.data)
```

Getting the following error when trying...

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/boto/rds/__init__.py", line 1156, in get_log_file
    logfile =  self.get_object('DownloadDBLogFilePortion', params, LogFileObject)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1204, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://rds.amazonaws.com/doc/2013-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
    <Message>This file contains binary data and should be downloaded instead of viewed.</Message>
  </Error>
  <RequestId>d0e886e9-6974-11e4-9a51-a951e19837bd</RequestId>
</ErrorResponse>
```

**Comment by sidwy** [comment]
Any updates here. I am getting the same error.

**Comment by ananthulasrikar** [comment]
same here :(
