### ISSUE TITLE
Inconsistant behavior when setting/getting S3 key metadata

### ISSUE THREAD

**Issue by gongchengshi** [boto/boto#2798]
boto version: 2.34.0

I noticed that setting the attributes listed on line 90 of boto/s3/key.py has no effect when writing a key. These attributes correspond to the special metadata fields: _cache-control, content-disposition, content-encoding, content-language, content-md5, content-type, x-robots-tag, expires_. However, after setting the this metadata using key.set_metadata() and then calling HEAD using key.get_key(), the attributes are set. I think this is inconsistent and unexpected.

Additionally, after setting these special metadata fields using key.set_metadata() or updating the metadata dict directly, writing the key, and then calling key.get_key() the key.metadata dict doesn't contain the metadata that was just set. Again this is inconsistent and unexpected. 

This is especially problematic when attempting to add metadata to an existing key using key.copy() because the special metadata fields won't get copied over even though the key.metadata dict was explicitly copied in code.

See the unit test below. I've also attached screen captures from the S3 console that correspond with points in the code. I expected everything in the screen capture to show up in key.metadata when it is queried.

``` python
import uuid
import zlib
import time
import unittest
from boto.s3.connection import S3Connection
from boto.s3.key import Key
from aws.constants import AwsAccessKey, AwsSecretKey


class SystemHeaderSetterTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        s3_conn = S3Connection(AwsAccessKey, AwsSecretKey)
        bucket_name = 'd5372b8d-69eb-4aea-97a6-2c31c5d999ad'
        cls._bucket = s3_conn.lookup(bucket_name) or s3_conn.create_bucket(bucket_name)

    def test_use_content_encoding_setter(self):
        key_name = str(uuid.uuid1())
        key = Key(self._bucket, key_name)

        key.content_encoding = 'deflate'

        key.set_contents_from_string(zlib.compress('yada yada yada'), reduced_redundancy=True)

        time.sleep(2)  # See test_use_content_encoding_setter.png

        key = self._bucket.get_key(key_name)

        self.assertEqual('deflate', key.content_encoding)  # This will fail
        expected_metadata = {
            'content-encoding': 'deflate'
        }
        self.assertDictContainsSubset(expected_metadata, key.metadata)  # This will fail

    def test_use_set_metadata(self):
        key_name = str(uuid.uuid1())
        key = Key(self._bucket, key_name)

        key.set_metadata('content-encoding', 'deflate')
        key.set_metadata('my_metadata', 'bogus')

        key.set_contents_from_string(zlib.compress('yada yada yada'), reduced_redundancy=True)

        time.sleep(2)  # See test_use_set_metadata.png

        key = self._bucket.get_key(key_name)

        self.assertEqual('deflate', key.content_encoding)  # This will pass
        expected_metadata = {
            'content-encoding': 'deflate',
            'my_metadata': 'bogus'
        }
        self.assertDictContainsSubset(expected_metadata, key.metadata)  # This will fail

    def test_copy_metadata(self):
        key_name = str(uuid.uuid1())
        key = Key(self._bucket, key_name)

        key.set_metadata('content-language', 'en')  # system header names must be lowercase?
        key.set_metadata('my_metadata', 'bogus')

        key.set_contents_from_string(zlib.compress('yada yada yada'), reduced_redundancy=True)

        time.sleep(2)  # test_copy_metadata-first_sleep.png

        # Oops I forgot to set the Content-Encoding header
        key = self._bucket.get_key(key_name)
        key.set_metadata('content-encoding', 'deflate')
        key.copy(key.bucket.name, key.name, key.metadata, preserve_acl=True, reduced_redundancy=True)

        time.sleep(2)  # test_copy_metadata-second_sleep.png

        key = self._bucket.get_key(key_name)

        self.assertEqual('deflate', key.content_encoding)  # This will pass
        self.assertEqual('en', key.content_language)  # This will fail!
        self.assertIn('content-language', key.metadata.keys())  # This will fail
        expected_metadata = {
            'content-encoding': 'deflate',
            'content-language': 'en',
            'my_metadata': 'bogus'
        }
        self.assertDictContainsSubset(expected_metadata, key.metadata)  # This will fail
```

Test results

```
Failure
Traceback (most recent call last):
  File "/home/jeremy/Sandbox/add_metadata/boto_issue.py", line 76, in test_copy_metadata
    self.assertEqual('en', key.content_language)  # This will fail!
AssertionError: 'en' != None

Failure
Traceback (most recent call last):
  File "/home/jeremy/Sandbox/add_metadata/boto_issue.py", line 29, in test_use_content_encoding_setter
    self.assertEqual('deflate', key.content_encoding)  # This will fail
AssertionError: 'deflate' != None

Failure
Traceback (most recent call last):
  File "/home/jeremy/Sandbox/add_metadata/boto_issue.py", line 53, in test_use_set_metadata
    self.assertDictContainsSubset(expected_metadata, key.metadata)  # This will fail
AssertionError: Missing: 'content-encoding'
```

test_use_content_encoding_setter.png
![test_use_content_encoding_setter](https://cloud.githubusercontent.com/assets/2213992/5303907/854f3bf0-7ba2-11e4-9756-e6d499459a53.png)

test_use_set_metadata.png
![test_use_set_metadata](https://cloud.githubusercontent.com/assets/2213992/5303905/854591ea-7ba2-11e4-8477-6d95ca1a9765.png)

test_copy_metadata-first_sleep.png
![test_copy_metadata-first_sleep](https://cloud.githubusercontent.com/assets/2213992/5303906/854d7568-7ba2-11e4-8be4-2c46a1aeace0.png)

test_copy_metadata-second_sleep.png
![test_copy_metadata-second_sleep](https://cloud.githubusercontent.com/assets/2213992/5303908/854ffb94-7ba2-11e4-9b5c-381f80053c3a.png)

**Comment by opottone** [comment]
Different metadata values are handled differently. Special metadata fields are object fields, e.g. key.cache_control, and everything else is in the dict key.metadata. This is somewhat inconsistent and easily leads to trouble.

Possible solution: keep it simple, store all metadata in key.metadata. Use __setattr__ and __getattr__ for the special fields, so that referencing key.cache_control, for instance, works as before.
