### ISSUE TITLE
Unable to call query_2 after call describe method - DynamoDB2 module

### ISSUE THREAD

**Issue by pauloubuntu** [boto/boto#2828]
Hi,

I've noticed a weird behaviour when trying to query anything after called describe method. Here is an example:

Script that fails because of describe method is called before query:
```Python
from boto.dynamodb2.table import Table

invitationTable = Table("INVITATION")
invitationTable.describe()

oldInvitationResultSet = invitationTable.query_2(
    index='date_when_gsi-index',
    date_when_gsi__eq='20141226',
    max_page_size=20
)

for user in oldInvitationResultSet:
    print user['owner_user_name'], user['user_name']
```

That outputs :
```
Traceback (most recent call last):
  File "/Users/paulo.rodenas/workspaceIdea/brejaadmin/02-Database/02-Routine/02-InvitationsRemoval/OldInvitationRemoval/script.py", line 15, in <module>
    max_page_size=20
  File "/Users/paulo.rodenas/workspaceIdea/boto/boto/dynamodb2/table.py", line 984, in query_2
    "You must specify more than one key to filter on."
boto.dynamodb2.exceptions.QueryError: You must specify more than one key to filter on.
```

The same script but without calling describe method:

```Python
from boto.dynamodb2.table import Table

invitationTable = Table("INVITATION")
#invitationTable.describe()

oldInvitationResultSet = invitationTable.query_2(
    index='date_when_gsi-index',
    date_when_gsi__eq='20141226',
    max_page_size=20
)

for user in oldInvitationResultSet:
    print user['owner_user_name'], user['user_name']
```

That outputs:

```
GUIJOU CHARLOUMICH
GUIJOU HDRI
GUIJOU GODASSE45

Process finished with exit code 0
```

**Comment by pauloubuntu** [comment]
Closing this issue since the PR #2829 has been merged.

**Comment by xethorn** [comment]
:+1:
