### ISSUE TITLE
SSLError: ('The read operation timed out',) in bucket_lister

### ISSUE THREAD

**Issue by joe42** [boto/boto#2830]
The SSLError occurs often when iterating through the contents of my bucket, but not always. 
This seems to be a related bug:
https://bugs.launchpad.net/duplicity/+bug/505739
The complete log is here: https://gist.github.com/joe42/12f738d81cbbde3e4861
There seem to be a lot of log files, which might be the reason for the exception.

```
======================================================================
ERROR: BulkGetMetadataAmazonStore: getting used space
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/joe/projects/eclipse_ws/nubisave_clone/nubisave/CloudFusion/cloudfusion/tests/store_tests.py", line 391, in _test_get_used_space
    def _test_get_used_space(store):
  File "/home/joe/projects/eclipse_ws/nubisave_clone/nubisave/CloudFusion/cloudfusion/store/s3/amazon_store.py", line 217, in get_used_space
    for key in self.bucket:
  File "/usr/local/lib/python2.7/dist-packages/boto-2.30.0-py2.7.egg/boto/s3/bucketlistresultset.py", line 32, in bucket_lister
    encoding_type=encoding_type)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.30.0-py2.7.egg/boto/s3/bucket.py", line 471, in get_all_keys
    '', headers, **params)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.30.0-py2.7.egg/boto/s3/bucket.py", line 400, in _get_all
    body = response.read()
  File "/usr/local/lib/python2.7/dist-packages/boto-2.30.0-py2.7.egg/boto/connection.py", line 413, in read
    self._cached_response = httplib.HTTPResponse.read(self)
  File "/usr/lib/python2.7/httplib.py", line 549, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 607, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/usr/lib/python2.7/httplib.py", line 664, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 709, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 603, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)
```

**Comment by Captainkrtek** [comment]
Can you provide a snippet of your code?

**Comment by joe42** [comment]
Hi,

The code is available on github:
https://github.com/joe42/CloudFusion/blob/master/cloudfusion/store/s3/amazon_store.py#L217

Is it possible that thsi is due to the timeout I set? I thought the timeout is just for connecting the socket though.
    boto.config.set('Boto','http_socket_timeout','10')

**Comment by dlstadther** [comment]
@joe42 I have also encountered this issue. Did you find it to be a random occurrence? Or did you find a solution? Thanks

**Comment by joe42** [comment]
It did occur randomly, but as far as I can remember still quite often when you have many files in your bucket. Many as in thousands ob objects. I think this occurred when I executed stress tests. You might try to remove the log files, and install a retry and cache mechansim, but I cannot provide an actual solution.
