### ISSUE TITLE
health_check cannot run update method because missing self.connection

### ISSUE THREAD

**Issue by russellballestrini** [boto/boto#2931]
It seems healthcheck expects to have access to self.connection when running ```update()``` method, but this isn't an attribute.  The load balancer does have a connection though, so there is a work around for now...

```
>>> proxy_elb, web_elb = hvpc.get_load_balancers()
>>> proxy_elb
LoadBalancer:ficops01-proxy-elb
>>> hc = proxy_elb.health_check
>>> hc.healthy_threshold = 3
>>> hc.unhealthy_threshold = 3
>>> hc.interval = 20
```

This doesn't work:

```
>>> proxy_elb.health_check.update()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/russellballestrini/env/lib/python2.7/site-packages/boto/ec2/elb/healthcheck.py", line 83, in update
    new_hc = self.connection.configure_health_check(self.access_point,
AttributeError: 'HealthCheck' object has no attribute 'connection'
```

Work Around:
```
>>> proxy_elb.configure_health_check(hc)
HealthCheck:TCP:3128
```

**Comment by russellballestrini** [comment]
Hey anyone have some time to code review either of my proposed PRs that fix this issue?
