### ISSUE TITLE
ConditionalCheckFailedException: 400 Bad Request

### ISSUE THREAD

**Issue by zhujunmd** [boto/boto#2967]
My code is like this:
    dynamo_item = Item(products_table, data=item)
    dynamo_item.save()

If one item is already exited in the table (same key), it will raise the following exception. How to do "update" if the item is existed. Thanks!

	Traceback (most recent call last):
	  File "C:\Python27\lib\site-packages\twisted-15.0.0-py2.7-win32.egg\twisted\internet\defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "C:\Python27\lib\site-packages\twisted-15.0.0-py2.7-win32.egg\twisted\internet\defer.py", line 840, in _cbDeferred
	    self.callback(self.resultList)
	  File "C:\Python27\lib\site-packages\twisted-15.0.0-py2.7-win32.egg\twisted\internet\defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "C:\Python27\lib\site-packages\twisted-15.0.0-py2.7-win32.egg\twisted\internet\defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "C:\Python27\lib\site-packages\twisted-15.0.0-py2.7-win32.egg\twisted\internet\defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "D:\Mingdabeta\projects\workspace\scrapy\avarsha\avarsha\pipelines.py", line 25, in process_item
	    dynamo_item.save()
	  File "C:\Python27\lib\site-packages\boto\dynamodb2\items.py", line 455, in save
	    returned = self.table._put_item(final_data, expects=expects)
	  File "C:\Python27\lib\site-packages\boto\dynamodb2\table.py", line 671, in _put_item
	    self.connection.put_item(self.table_name, item_data, **kwargs)
	  File "C:\Python27\lib\site-packages\boto\dynamodb2\layer1.py", line 1510, in put_item
	    body=json.dumps(params))
	  File "C:\Python27\lib\site-packages\boto\dynamodb2\layer1.py", line 2842, in make_request
	    retry_handler=self._retry_handler)
	  File "C:\Python27\lib\site-packages\boto\connection.py", line 953, in _mexe
	    status = retry_handler(response, i, next_sleep)
	  File "C:\Python27\lib\site-packages\boto\dynamodb2\layer1.py", line 2879, in _retry_handler
	    response.status, response.reason, data)
	boto.dynamodb2.exceptions.ConditionalCheckFailedException: ConditionalCheckFailedException: 400 Bad Request
	{u'message': u'The conditional request failed', u'__type': u'com.amazonaws.dynamodb.v20120810#ConditionalCheckFailedException'}

**Comment by vburenin** [comment]
dynamo_item.save(overwrite=True)

**Comment by zhujunmd** [comment]
Thanks!

**Comment by jobn123** [comment]
thanks it's useful
