### ISSUE TITLE
calling Table.describe() immediately after calling Table.delete_global_secondary_index(...) fails

### ISSUE THREAD

**Issue by millarm** [boto/boto#2978]
Needs to handle missing projection in the return value

>>> table.delete_global_secondary_index('DeviceIDIndex')
True
>>> table.describe()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/millarm/projects/tellybug/webserver/lib/python2.7/site-packages/boto/dynamodb2/table.py", line 376, in describe
    self.global_indexes = self._introspect_global_indexes(raw_global_indexes)
  File "/Users/millarm/projects/tellybug/webserver/lib/python2.7/site-packages/boto/dynamodb2/table.py", line 330, in _introspect_global_indexes
    self._PROJECTION_TYPE_TO_INDEX.get('global_indexes'))
  File "/Users/millarm/projects/tellybug/webserver/lib/python2.7/site-packages/boto/dynamodb2/table.py", line 295, in _introspect_all_indexes
    if field['Projection']['ProjectionType'] == 'ALL':
KeyError: 'Projection'

Reproduced using tip of develop branch @ Commit a36e6d471642028f17b3f9b6451eb7eccbd1f436

**Comment by pauloubuntu** [comment]
Hi @millarm 

Sorry for my late reply,I'll take a look at this when I get home. Thanks

**Comment by aronrosenberg** [comment]
Somewhat related to this issue: The official docs at http://docs.pythonboto.org/en/latest/ref/dynamodb2.html#module-boto.dynamodb2.table indicate that the new delete_global_secondary_index and create_global_secondary_index functions exist in the 2.36.0 release, but they don't infact.

**Comment by pauloubuntu** [comment]
@aronrosenberg the link you provided points to the latest release which I think it was v2.37.0 by the time. 

Actually the new methods for handling add/update/delete global indexes after table creation were added on v2.37.0 but it was only made available on v2.38.0 which was released on April, 8th.

**Comment by pauloubuntu** [comment]
Hi @millarm,

I must confess I couldn't find a way to reproduce the error you're getting. Could you share some code where it happens?

**Comment by aronrosenberg** [comment]
@pauloubuntu To reproduce this issue you can just use the AWS console to delete a global secondary index and then run a script which calls describe_table on the table while that index is being deleted.

The core issue is that an index in the DELETING state doesn't have any values for Projection or Keys returned in the response call.

**Comment by rj919** [comment]
I am also experiencing this problem. Currently using 2.38.

The problem only seems to occur when interacting with dynamoDB on AWS. Use of dynamoDB local works just fine.

While this problem is being fixed, is there a workaround? Or should I just hardcode a timer?
