### ISSUE TITLE
EC2Connection.deregister_image( ..., delete_snapshot=True ) doesn't work reliably

### ISSUE THREAD

**Issue by hannes-ucsc** [boto/boto#3019]
There seems to be a race condition between deregister_image and delete_snapshot. I hit it 1 in 5 times today.

```xml
<Response>
  <Errors>
    <Error>
      <Code>InvalidSnapshot.InUse</Code>
      <Message>The snapshot snap-6c6e383d is currently in use by ami-f74260c7</Message>
    </Error>
  </Errors>
  <RequestID>9a7327c0-52fd-46b8-8a92-e07d908bbaf2</RequestID>
</Response>
```

In fact, I am surprised by the current implementation of delete_snapshot=True because deregister_image is not blocking and it can take up to a few minutes before the image is gone.

I don't know what the remedy is but I'll try working around it by catching the InUse and retrying. However, there is also the chance that a snapshot is referenced by more than one image in which case this strategy is not going to work. Alternatively, one could wait for the image to disappear and then remove the snapshot. In fact, I'll try both.

**Comment by jonathanwcrane** [comment]
Is it really possible for a snapshot to be referenced by more than one image?

**Comment by hannes-ucsc** [comment]
Good point. Probably not. I tried copying an AMI and the snapshot was copied, too. The only other way to create an AMI is with RegisterImage and that doesn't use snapshots.

**Comment by hannes-ucsc** [comment]
So waiting for the AMI to disappear does not seem to fix the race. I'm still getting `InvalidSnapshot.InUse` even though `get_image( ami_id )` returns nothing for the AMI ID that was deregistered shortly before.

**Comment by jonathanwcrane** [comment]
That's funny because I have some code that deletes AMIs then finds all it's "orphan" snapshots (the snapshots that aren't included in the deletion when DeleteSnapshot=True) and I've never run into this problem.  Perhaps you could include some code?

**Comment by hannes-ucsc** [comment]
https://github.com/BD2KGenomics/cgcloud-core/blob/aff85666c4619100d03509ca68b8822b55a5d9cf/src/cgcloud/core/box.py#L904

I think this is a race condition in EC2, so if enough time passes between deregistering the AMI and the deletion of the associated snapshot, chances are that you'll never hit it.

**Comment by jonathanwcrane** [comment]
So I may not be reading this code correctly, but it looks like you're manually deleting the root device that was part of the snapshot; if I understand correctly, this is what the delete_snapshot=True parameter in the AWS API does for your automatically.  In fact that may be precisely why they provided that.  Assuming these are true, why aren't you just deregistering the AMI with the delete_snapshot=True parameter and letting AWS worry about it, rather than managing that yourself?

**Comment by hannes-ucsc** [comment]
I am managing it myself because there is this race condition that causes boto's `deregister_image( ..., delete_snapshot=True )` to sometimes fail with the error I mention in the OP. So I am emulating `deregister_image( ..., delete_snapshot=True )` but with two differences: I wait until the AMI disappears and I retry the snapshot deletion if it fails with an error that I think is the symptom of the race. I think that waiting makes the race less likely and retrying works around the race by, well, just retrying the operation until it succeeds.

The root device stuff is part of emulating `deregister_image()`. There is a minor difference between my implementation and boto's (see #3020) but you can largely ignore that for the sake of this discussion.

**Comment by jonathanwcrane** [comment]
Interesting.  Have you thought of forking boto and updating the code and submitting a pull request?

**Comment by hannes-ucsc** [comment]
I have. I want to wait a little until the dust has settled so I can be sure that my workaround is effective.

**Comment by bobthomson70** [comment]
I don't quite see how this is related to #846 / #1219 ?
Getting a similar apparent race condition when calling image.deregister to deregister old AMI images -

image.deregister(delete_snapshot=True, dry_run=False)

Sometimes this will fail with an exception -

20:15:43 Traceback (most recent call last):
20:15:43   File "/home/infra.ansible/.scripts/ami/python/ami_backup.py", line 100, in <module>
20:15:43     image.deregister(delete_snapshot=True, dry_run=False)
20:15:43   File "/usr/lib/python2.6/site-packages/boto/ec2/image.py", line 335, in deregister
20:15:43     dry_run=dry_run
20:15:43   File "/usr/lib/python2.6/site-packages/boto/ec2/connection.py", line 396, in deregister_image
20:15:43     return result and self.delete_snapshot(snapshot_id)
20:15:43   File "/usr/lib/python2.6/site-packages/boto/ec2/connection.py", line 2501, in delete_snapshot
20:15:43     return self.get_status('DeleteSnapshot', params, verb='POST')
20:15:43   File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1227, in get_status
20:15:43     raise self.ResponseError(response.status, response.reason, body)
20:15:43 boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
20:15:43 <?xml version="1.0" encoding="UTF-8"?>
20:15:43 <Response><Errors><Error><Code>InvalidSnapshot.InUse</Code><Message>The snapshot snap-45705568 is currently in use by ami-18174a6f</Message></Error></Errors><RequestID>6ea53939-c576-47a8-ba09-d5fdf2946ebf</RequestID></Response>

Raised a case with Amazon who advised the delete snapshot and deregister AMI occur at essentially the same time which, on occasion means the AMI deregister fails as the AMI is in use - presumably because it still has the snapshot associated with it.

I'm no python dev but it seems to me there maybe is an assumption about the ordering here that isn't true given the async nature of Amazon's API calls - that is the snapshot should be deleted for sure first before attempting to deregister the image.

This is with boto 2.38.0-1

**Comment by jonathanwcrane** [comment]
I know I had a support ticket open for another issue related to checking for an ongoing_restore of an S3/Glacier object.  The solution they came back with was "have you tried boto3?"  I did and boto3 is awesome.  AFAIK all ongoing development/enhancement efforts are focused there.  Is boto3 an option for you?

**Comment by bobthomson70** [comment]
Hi, thanks for your comment. boto3 isn't really an option for us just now, no. It looks like boto3 decouples the AMI deletion from the snapshot deletion so the caller has to remove snapshots before AMIs and thus won't get the issue we're getting in 2.38.

As it is, I've added some code that will move on to the next image if we can get an exception, as for our use case it doesn't really matter if the image isn't deleted one run, if it will be deleted on the next. Main issue we had was the exception not bring captured, causing the whole script to fall over and miss backups as well as the removal of redundant AMIs. So hopefully it will be OK now. Would've been good to see a fix in boto2* but fair enough if boto3 is the way to go longer term. Cheers.

**Comment by esc-** [comment]
I ran into this issue while writing a script to create a new instance with a Role assigned to it from an image of the target instance. (I know my code is a bit messy, but it got the job done)

In my case, delete_snapshot=True was never deleting the snapshots when deregistering the image. I was able to work around this issue in boto 2.42.0 by reading block_device_mapping from the Image:

```
conn = EC2Connection()

filter = {'instance-id' : targetInstance}
instance = conn.get_all_instances(filters=filter)[0].instances[0]
imageID = conn.create_image(instance.id,"test image")
image = conn.get_all_images(image_ids=imageID)
...
for s in image[0].block_device_mapping.itervalues():
    snapshots.append(s.snapshot_id)
conn.deregister_image(imageID)
for s in snapshots:
    print("Deleting snapshot " + s)
    conn.delete_snapshot(s)
```
