### ISSUE TITLE
boto does not read /etc/boto.cfg if user==nobody

### ISSUE THREAD

**Issue by RichardBronosky** [boto/boto#3044]
## Given

/etc/boto.cfg

    [default]
    aws_access_key_id = Hunter2
    aws_secret_access_key = Hunter2

hack.py

    # hack.py
    import os
    import pwd
    import boto

    if False:
        pw = pwd.getpwnam('nobody')
        os.setgid(pw.pw_gid)
        os.setuid(pw.pw_uid)

    print file('/etc/boto.cfg').read()

    s3 = boto.connect_s3()
    bucket = s3.get_bucket('www-example-com')

## Expected results

    $ python hack.py
    
    [default]
    aws_access_key_id = Hunter2
    aws_secret_access_key = Hunter2

    Traceback (most recent call last):
      File "/tmp/hack.py", line 13, in <module>
        bucket = s3.get_bucket('www-example-com')
      File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 502, in get_bucket
        return self.head_bucket(bucket_name, headers=headers)
      File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 535, in head_bucket
        raise err
    S3ResponseError: S3ResponseError: 403 Forbidden

You will actually get these results given the 2 files above. The 403 is expected because the credentials don't grant you access to the bucket.

## Actual results

    $ sudo -u nobody python hack.py

    [default]
    aws_access_key_id = Hunter2
    aws_secret_access_key = Hunter2

    Traceback (most recent call last):
      File "/tmp/hack.py", line 12, in <module>
        s3 = boto.connect_s3()
      File "/usr/local/lib/python2.7/dist-packages/boto/__init__.py", line 141, in connect_s3
        return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 190, in __init__
        validate_certs=validate_certs, profile_name=profile_name)
      File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 569, in __init__
        host, config, self.provider, self._required_auth_capability())
      File "/usr/local/lib/python2.7/dist-packages/boto/auth.py", line 985, in get_auth_handler
        'Check your credentials' % (len(names), str(names)))
    boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials

You will actually get these results given the 2 files above. However, **you should get the same results** from both commands.

It is clearly *able* to read `/etc/boto.cfg` as user nobody. It just doesn't.

## Reproducing

This test was run on a virgin [dockerfile/python] (https://dockerfile.github.io/#/python) instance via `docker run -t -i dockerfile/python`.

**Comment by RichardBronosky** [comment]
It may also be worth noting that the following test yields the expected results:

    export AWS_ACCESS_KEY_ID=Hunter2; export AWS_SECRET_ACCESS_KEY=Hunter2; sudo -Eu nobody python hack.py
