### ISSUE TITLE
Glacier: archive download fails without verify_hashes=False

### ISSUE THREAD

**Issue by supki** [boto/boto#3059]
Hello!

When I try to download the result of a completed job I get the following exception unless I specify `verify_hashes=False`:

```
>>> job.download_to_file("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/m/.local/lib/python3.4/site-packages/boto/glacier/job.py", line 123, in download_to_file
    verify_hashes, retry_exceptions)
  File "/var/m/.local/lib/python3.4/site-packages/boto/glacier/job.py", line 159, in _download_to_fileob
    actual_tree_hash, expected_tree_hash, byte_range))
boto.glacier.exceptions.TreeHashDoesNotMatchError: The calculated tree hash b'7a3ad924132a50f574e79d70ea845ce45e2cd5e580e47d02cea410bedb0333f6' does not match the expected tree hash 7a3ad924132a50f574e79d70ea845ce45e2cd5e580e47d02cea410bedb0333f6 for the byte range (0, 4194303)
```

The hashes are the same, so it looks like a missing type conversion somewhere.

Python 3.4.1
boto 2.36.0

**Comment by jsnshrmn** [comment]
I just ran across this myself
Python 3.4.2
2.36.0
