### ISSUE TITLE
New Dynamodb types broke working query (2.35.2 and up)

### ISSUE THREAD

**Issue by joonathan** [boto/boto#3094]
For a table:

`Schema(user_id:timestamp)`
`{u'RangeKeyElement': {u'AttributeName': u'timestamp', u'AttributeType': u'N'}, u'HashKeyElement': {u'AttributeName': u'user_id', u'AttributeType': u'N'}}`

Iterating a query as simple as `t = table.query(hash_key=2)` would cause:

```
python2.7/site-packages/boto/dynamodb/types.py", line 336, in decode
    if len(attr) > 1 or not attr:
TypeError: object of type 'int' has no len()
```

Before with 2.35.0 for example:
```
>>> import boto
>>> boto.__version__
'2.35.0'
>>> conn = boto.connect_dynamodb('key', 'secret')
>>> table = conn.get_table('table')
>>> t = table.query(hash_key=2)
>>> t.count
87
```

With 2.35.2 and newer:
```
>>> import boto
>>> boto.__version__
'2.35.0'
>>> conn = boto.connect_dynamodb('key', 'secret')
>>> table = conn.get_table('table')
>>> t = table.query(hash_key=2)
>>> t.count
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joonathan/.virtualenvs/Project/lib/python2.7/site-packages/boto/dynamodb/layer2.py", line 67, in count
    self.response
  File "/Users/joonathan/.virtualenvs/Project/lib/python2.7/site-packages/boto/dynamodb/layer2.py", line 92, in response
    return self.next_response() if self._response is None else self._response
  File "/Users/joonathan/.virtualenvs/Project/lib/python2.7/site-packages/boto/dynamodb/layer2.py", line 104, in next_response
    self._response = self.callable(**self.kwargs)
  File "/Users/joonathan/.virtualenvs/Project/lib/python2.7/site-packages/boto/dynamodb/layer1.py", line 530, in query
    object_hook=object_hook)
  File "/Users/joonathan/.virtualenvs/Project/lib/python2.7/site-packages/boto/dynamodb/layer1.py", line 127, in make_request
    return json.loads(response_body, object_hook=object_hook)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/Users/joonathan/.virtualenvs/Project/lib/python2.7/site-packages/boto/dynamodb/types.py", line 347, in decode
    return decoder(attr[dynamodb_type])
  File "/Users/joonathan/.virtualenvs/Project/lib/python2.7/site-packages/boto/dynamodb/types.py", line 374, in _decode_m
    return dict([(k, self.decode(v)) for k, v in attr.items()])
  File "/Users/joonathan/.virtualenvs/Project/lib/python2.7/site-packages/boto/dynamodb/types.py", line 336, in decode
    if len(attr) > 1 or not attr:
TypeError: object of type 'int' has no len()
```

**Comment by pauloubuntu** [comment]
Hi @joonathan,

AFAIK Table.query has been deprecated while ago for a couple reasons. You should try using Table.query_2.

http://boto.readthedocs.org/en/latest/dynamodb2_tut.html#querying

Let me know if it works for you

**Comment by joonathan** [comment]
Indeed, with boto.dynamodb2.query_2 I can get it working with a small rewrite.
Is it worth keeping the ticket open or is the non-backwards-compatible change in 2.35.2 to original query not worth fixing?

**Comment by pauloubuntu** [comment]
I think you should keep it opened for now.

**Comment by petterreinholdtsen** [comment]
I see the same problem when doing table.scan().  Is there some scan_2()?  I could not find it.

**Comment by PauloMigAlmeida** [comment]
@petterreinholdtsen not that I'm aware of. Considering that boto3 has been released for a while now (and all new features and fixes are centralised there), it's only natural that a few things will start no longer working on boto as it used to.

Is it a possibility for you to use boto3 instead? it's fairly simple and it has also a high-level interface for DDB...so the migration shouldn't be that painful

**Comment by petterreinholdtsen** [comment]
Thank you for your swift reply. :)

[Paulo Miguel Almeida]
> Is it a possibility for you to use boto3 instead? it's fairly simple
> and it has also a high-level interface for DDB...so the migration
> shouldn't be that painful

At the moment I use <URL: https://tracker.debian.org/pkg/python-boto >.
I'll give <URL: https://tracker.debian.org/pkg/python-boto3 > a go.

I am not too keen on using non-Debian packages, with all its
implications regarding support and security tracking.

--
Happy hacking
Petter Reinholdtsen
