### ISSUE TITLE
UnexpectedHTTPResponseError with Python3

### ISSUE THREAD

**Issue by xsuchy** [boto/boto#3110]
I am trying to migrate glacier-cli to python3 and I just find that:
```
python3 ./glacier.py --region=eu-west-1 archive upload --name "test.JPG" Fotky /tmp/test.jpg
```
generate following error:
```
Traceback (most recent call last):
  File "./glacier.py", line 746, in <module>
    App().main()
  File "./glacier.py", line 732, in main
    self.args.func()
  File "./glacier.py", line 507, in archive_upload
    file_obj=self.args.file, description=name)
  File "/usr/lib/python3.4/site-packages/boto/glacier/vault.py", line 178, in create_archive_from_file
    writer.close()
  File "/usr/lib/python3.4/site-packages/boto/glacier/writer.py", line 228, in close
    self.partitioner.flush()
  File "/usr/lib/python3.4/site-packages/boto/glacier/writer.py", line 79, in flush
    self._send_part()
  File "/usr/lib/python3.4/site-packages/boto/glacier/writer.py", line 75, in _send_part
    self.send_fn(part)
  File "/usr/lib/python3.4/site-packages/boto/glacier/writer.py", line 222, in _upload_part
    self.uploader.upload_part(self.next_part_index, part_data)
  File "/usr/lib/python3.4/site-packages/boto/glacier/writer.py", line 129, in upload_part
    content_range, part_data)
  File "/usr/lib/python3.4/site-packages/boto/glacier/layer1.py", line 1279, in upload_part
    response_headers=response_headers)
  File "/usr/lib/python3.4/site-packages/boto/glacier/layer1.py", line 119, in make_request
    raise UnexpectedHTTPResponseError(ok_responses, response)
boto.glacier.exceptions.UnexpectedHTTPResponseError: Expected (204,), got (400, b'{"code":"InvalidParameterValueException","message":"Invalid Content-Range: bytes%200-1725332/*","type":"Client"}')
```
It is quite strange because the same code on python2 pass without problem. I am using:
python-boto-2.34.0-4.fc21.noarch, python3-boto-2.34.0-4.fc21.noarch
But lookign at the recent code I find no change in those parts nor some relevant code. So I believe that this problem is in master as well.

**Comment by AkshivBaluja** [comment]
You could try this fix : - 
https://github.com/boto/boto/issues/2524
I had a similar issue, it worked out for me.

**Comment by toyg** [comment]
The problem of that fix is that space is added to the "safe" characters list, which I guess might not be acceptable for some of the other services. Or at least that's the only explanation I can find for not merging it and keeping glacier support utterly broken for months.

Another workaround would be to remove the call to `super(Layer1, self).make_request(...)` in `glacier.Layer1.make_request` and instead embed the contents of that call; this would allow you to set _headers_quoted to True on the HTTPConnection object before the request is actually sent, but I don't know if there are situations in which headers sent to glacier through boto might actually need to be quoted.
