### ISSUE TITLE
The action DescribeInstanceTypes is not valid for this web service

### ISSUE THREAD

**Issue by galindro** [boto/boto#3137]
Is there a way to get all ec2 instance types available on Amazon? I've tried this, but no success:

```python
import boto.ec2
ec2 = boto.ec2.connect_to_region('sa-east-1')
ec2.get_all_instance_types()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/ec2/connection.py", line 4389, in get_all_instance_types
    return self.get_list('DescribeInstanceTypes', params, [('item', InstanceType)], verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidAction</Code><Message>The action DescribeInstanceTypes is not valid for this web service.</Message></Error></Errors><RequestID>e02aad26-063f-4342-85d3-1c73f5d346d8</RequestID></Response>
```

**Comment by dclark87** [comment]
I would also be interested in this

**Comment by fvillain** [comment]
I get exactly the same problem

**Comment by pdecat** [comment]
DescribeInstanceTypes is Eucalyptus-specific according to http://blogs.mindspew-age.com/2014/06/13/coreos-cloudinit-config-for-docker-storage-management
