### ISSUE TITLE
Send email template error with Amazon SES

### ISSUE THREAD

**Issue by vandinhchuong** [boto/boto#3160]
Hi guys,

I use Amazon SES for send email so boto is my choice. But so difficult to get examples about SES. Thanks a lot if you have any idea how to fix below code.

***This my code:***
```
# -*- coding: utf-8 -*-
import types

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import COMMASPACE

from boto.ses import SESConnection
from boto.regioninfo import RegionInfo

class AmazonSender(object):

  client = None

  def __init__(self, aws_key, aws_secret):
    self.aws_key = aws_key
    self.aws_secret = aws_secret
    print aws_key
    print aws_secret

  def send_email(self, sender,
                       to_addresses,
                       subject,
                       text,
                       html=None,
                       reply_addresses=None,
                       sender_ascii=None):
    if not sender_ascii:
      sender_ascii = sender

    client = self.get_client()

    message = MIMEMultipart('alternative')
    message.set_charset('UTF-8')

    message['Subject'] = _encode_str(subject)
    message['From'] = _encode_str(sender)

    message['To'] = _convert_to_strings(to_addresses)

    if reply_addresses:
      message['Reply-To'] = _convert_to_strings(reply_addresses)

    message.attach(MIMEText(_encode_str(text), 'plain'))

    if html:
      message.attach(MIMEText(_encode_str(html), 'html'))
    print sender
    print to_addresses
    return client.send_raw_email(source=sender, raw_message=message.as_string(),destinations=to_addresses)

  def vertify_email(self, email):
    client = self.get_client()
    return client.verify_email_address(email)

  def get_client(self):
    if not self.client:
    	region = RegionInfo(name="us-west-2", endpoint="email-smtp.us-west-2.amazonaws.com")
    	self.client = SESConnection(region=region, 
    		aws_access_key_id=self.aws_key, 
    		aws_secret_access_key=self.aws_secret,
    		debug=2)
    return self.client


#--- Helpers ----------------------------------------------
def _convert_to_strings(list_of_strs):
  if isinstance(list_of_strs, (list, tuple)):
    result = COMMASPACE.join(list_of_strs)
  else:
    result = list_of_strs
  return _encode_str(result)

def _encode_str(s):
  if type(s) == types.UnicodeType:
    return s.encode('utf8')
  return s

amazon_sender = AmazonSender('my_aws_key', 'my_aws_secrect')
amazon_sender.send_email(sender='support@mycompany.com',
                         to_addresses='bbcc@gmail.com',
                         subject='Hello friend',
                         text='Just a message',
                         html='<b>Just a message</b>',
                         sender_ascii="aabb@gmail.com")
```

***error log:***

```
reply: '220 email-smtp.amazonaws.com ESMTP SimpleEmailService-1062959777 a6csJr5CxCY5IjJmmsna\r\n'
Traceback (most recent call last):
  File "gtoken/utils/ses.py", line 113, in <module>
    sender_ascii="aabb@gmail.com")
  File "gtoken/utils/ses.py", line 77, in send_email
    return client.send_raw_email(source=sender, raw_message=message.as_string(),destinations=to_addresses)
  File "/data/dev.gtoken.com/venv/local/lib/python2.7/site-packages/boto/ses/connection.py", line 323, in send_raw_email
    return self._make_request('SendRawEmail', params)
  File "/data/dev.gtoken.com/venv/local/lib/python2.7/site-packages/boto/ses/connection.py", line 114, in _make_request
    h.parse(body)
  File "/data/dev.gtoken.com/venv/local/lib/python2.7/site-packages/boto/jsonresponse.py", line 55, in parse
    xml.sax.parseString(s, self)
  File "/usr/lib/python2.7/xml/sax/__init__.py", line 49, in parseString
    parser.parse(inpsrc)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 214, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: syntax error
```

Please guide me what is diffirent between ***sender*** and ***sender_ascii***. If I wanna asynchronous on send email, how do I?
I use boto version 2.38.0

Thanks in advance

**Comment by dstran** [comment]
What was your solution? I'm running into the same thing but for `GetSendQuota`. Any help would be greatly appreciated!
