### ISSUE TITLE
"ImportError: No module named boto" when Boto is installed on OS X. 

### ISSUE THREAD

**Issue by peterjohnjoseph** [boto/boto#3194]
I've been searching all night for a solution to this and nothing has worked so far. I have Python 2.7.8 installed, and boto is also installed on OS X 10.10.3. The problem is that unless I'm running as my root user, when I try to run the AWS ec2.py script while deploying with Ansible, I get-
`ERROR: Inventory script (ec2.py) had an execution error: Traceback (most recent call last):
  File "/Users/peterjohnjoseph/Sites/massvapors.com/ansible/ec2.py", line 121, in <module>
    import boto
ImportError: No module named boto`

Any idea what I might want to try? I'll give whatever information you need.

**Comment by guizello** [comment]
Hi, did you well exported both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY ?

**Comment by tjsoftworks** [comment]
peterjohn joseph: I'm looking at this pretty old issue and wondering if this is still an active issue. Can you please response with either a little detail and perhaps gist the ansible directory which contains the ec3.py file. It is my guess that this issue is not a boto issue exactly but is perhaps cause by an environment issue: perhaps a problem with your PATH, the setup of python on your machine or even the target machine you are building with your ansible code. Can you provide a little more context? It is hard to know with the information listed here.

If this issue is no long active perhaps we should close this issue?

**Comment by tjsoftworks** [comment]
To maintainers: There is no activity and apparently no further interest in this issue. I would retire this issue with recommendation to use boto3 - a stable environment path .... Personally it appears that most old issues in boto at this point fall into this category. The tag "closing-soon-if-no-response" is probably the right tone for everything that is 6 months or more old IMO.

**Comment by kyleknap** [comment]
Yeah usually when we apply the tag, we wait roughly a week to see if anybody responds, and if nobody responds we close. We just did not check back in on this issue, but thanks for commenting. Closing out issue on that note.

We usually put the closing-soon-if-no-response on an issue if we had a question or comment that was not responded back to, as we cannot really help unless we get more information. That being said I would be hesitant on putting that tag on all of the 6 month and older issues, especially if we have not commented on it as an issue may still be relevant but we may just have not got to it yet.

**Comment by FranckVE** [comment]
Hi,
I just had this exact issue when running an Ansible script in ec2.py on Mac OS.
Whether I installed boto or boto3 (changing the ec2.py script in such a case) with or without -U option, I kept having the error :
```
ERROR! Attempted to execute "aws/ec2.py" as inventory script: Inventory script (aws/ec2.py) had an execution error: Traceback (most recent call last):
  File "/Users/ ...username... /Documents/Ansible/ansible/aws/ec2.py", line 121, in <module>
    import boto
ImportError: No module named boto
```
I could not find any other solution but create the PYTHONPATH system variable :
```
export PYTHONPATH=/usr/local/lib/python2.7/site-packages
```
Not satisfying, as `boto` is the only module causing such issues.

**Comment by kaikuchn** [comment]
Same issue here.

**Comment by nbari** [comment]
This worked for me:

    pip install --upgrade --user boto3

**Comment by bl4ckmesa** [comment]
Had to do the same as nbaro, though my default pip isn't the one in fabric, I had to do `aperture:docker aaronr$ /usr/local/Cellar/fabric/1.14.0/libexec/bin/pip install boto3`

**Comment by PrithiviRajG** [comment]
It's not working for me too. Any suggestions?

**Comment by r2ad** [comment]
I ran into this same issue today.  I had python 2.7 installed on my Mac (there by default I presume).  I then installed homebrew and used it to get the latest version of python setup: **brew install python**

Then, I had two versions of python, which is okay.  Brew installed pip3 along with Python 3.6.5.

So then, I was able to run this to get boto3:  **pip3 install boto3**
To ensure that it is accessible, use the **python3** command, not the older python.  So in my case, I ran my code with:
`python3 signURL.py`

**Comment by Abdulrahimch** [comment]
Hi there,
go to Pipfile then install boto3, it works.
cd./Pipfile/
pipenv install boto3.

**Comment by takahiko-okada** [comment]
`pip2.7 install boto`
then it worked for me.

**Comment by adeshadk** [comment]
I was struggling with this on Ubuntu 18.4 as it keep install boto under python 3.6 but following wsolved the problem:
sudo pip2.7 install boto

**Comment by smartbenson1** [comment]
> This worked for me:
> 
> ```
> pip install --upgrade --user boto3
> ```

This worked for me as well!

**Comment by kruart** [comment]
I had a similar issue with Ansible(2.8.0) on Ubuntu 18.04 and fixed it in the following way:
For python 2
```
pip install boto
python ec2.py --list
```
For python 3
```
pip3 install boto
python3 ec2.py --list
```

**Comment by vmchale** [comment]
@FranckVE unfortunately setting the python path breaks all my python3 programs, viz. 

```
  AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by artforlife** [comment]
This issue is still alive and well. I am on Ubuntu 18.04

**Comment by madisettisunil** [comment]
This worked for Ubuntu 18.04.1  "apt install python-boto3"

**Comment by fanchuanster** [comment]
fistly, ensure boto is installed for python 2, while boto3 is for python 3.
if it still errors, explicitly add boto directory to sys.path.append(boto's path), get boto's path by:
pip show boto.
it works for me.

**Comment by DFYT42** [comment]
Had the exact same issue with my W10 and fixed this by installing boto3 with this command in both Python27 & Python34:

python -m pip install --user boto3

**Comment by manojbakkar** [comment]
thanks @DFYT42 `python3 -m pip install --user boto3` worked for me.

**Comment by nsarda2** [comment]
the error says it is not able to find boto module, though you have already installed it. Get the path where boto is installed .. and set it up in following env variable. this worked for me..

export PYTHONPATH=/home/ansadmin/.local/lib/python3.7/site-packages

**Comment by MatteoInfi** [comment]
none of this is working, same error

**Comment by jerrychong25** [comment]
> thanks @DFYT42 `python3 -m pip install --user boto3` worked for me.

This is working for my end, thank you!

**Comment by dchaid** [comment]
> Had the exact same issue with my W10 and fixed this by installing boto3 with this command in both Python27 & Python34:
> 
> python -m pip install --user boto3

works!

**Comment by jleape** [comment]
`conda install boto3` worked for me.
Python 3.8.8, conda distribution, mac os 11.2.1

**Comment by sfc-gh-srathod** [comment]
Run with `python3` instead of `python` 
Command
`python3 python_file.py`

**Comment by l3ocifer** [comment]
at the top of the ec2.py file, change "#!/usr/bin/env python" to 
"#!/usr/bin/env python3"

**Comment by mannawar** [comment]
```sudo apt-get install python3-boto3```
This solved the issue for me i am using 20.04 ubuntu

**Comment by ndahisaac** [comment]
i have this same issue which i work all night to get the solution but finally it was just to pip install boto

**Comment by intensecalm** [comment]
For me it was as per I3ocifer above: at the top of the ec2.py file, change "#!/usr/bin/env python" to
"#!/usr/bin/env python3"

**Comment by AseemWangoo** [comment]
Was facing the same problem but `conda install boto3 ` still worked 🥹
