### ISSUE TITLE
AWS Security Group failures when using protocols 50 or 51

### ISSUE THREAD

**Issue by rainmanh** [boto/boto#3212]
Hi
I am using ansible for creating security groups  and I  seem to have an strange issue when trying to use proto 50 or 51.
It seems I can create the new rule in the group but it fails when I try to re-run it.
I was posting in ansible:  https://github.com/ansible/ansible/issues/11177#issuecomment-109156842

And they mention the issue seems to be down boot

This is the error I get 

```````
invalid output was: Traceback (most recent call last):
  File "ansible-tmp-1433479180.89-23107385894344/ec2_group", line 1931, in <module>
    main()
  File "ansible-tmp-1433479180.89-23107385894344/ec2_group", line 304, in main
    group.authorize(rule['proto'], rule['from_port'], rule['to_port'], ip, grantGroup)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/securitygroup.py", line 203, in authorize
    dry_run=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 3192, in authorize_security_group
    params, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1223, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidPermission.Duplicate</Code><Message>the specified rule "peer: 12.12.12.12/32, protocol: 50, ALLOW" already exists</Message></Error></Errors><RequestID>fd1fb158-f31c-441c-9ce1-72dc6cc67a2c</RequestID></Response>

```````
thanks!

**Comment by rainmanh** [comment]
This has been fixed in ansible with an extra filter on their aws_group.py script.
Leaving this for the record if anybody gets into the same sort of issue.

https://github.com/ansible/ansible/issues/11177

Thanks!
