### ISSUE TITLE
Boto Package 2.38.0-1.el7 on EPEL: ImportError: No module named vendored

### ISSUE THREAD

**Issue by stieg** [boto/boto#3222]
Looks like EPEL pushed out a version of boto that doesn't load.  See the following code

```python
$ python
Python 2.7.5 (default, Jun 17 2014, 18:11:42)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/boto/__init__.py", line 27, in <module>
    from boto.pyami.config import Config, BotoConfigLocations
  File "/usr/lib/python2.7/site-packages/boto/pyami/config.py", line 29, in <module>
    from boto.compat import expanduser, ConfigParser, StringIO
  File "/usr/lib/python2.7/site-packages/boto/compat.py", line 58, in <module>
    from boto.vendored import six
ImportError: No module named vendored
```

This is on the following type of machine:

```sh
$ cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
```

Here is the package info from EPEL:

```
$ rpm -qi python-boto
Name        : python-boto
Version     : 2.38.0
Release     : 1.el7
Architecture: noarch
Install Date: Wed 10 Jun 2015 03:39:38 PM UTC
Group       : Development/Languages
Size        : 9743014
License     : MIT
Signature   : RSA/SHA256, Sat 11 Apr 2015 04:18:53 PM UTC, Key ID 6a2faea2352c64e5
Source RPM  : python-boto-2.38.0-1.el7.src.rpm
Build Date  : Fri 10 Apr 2015 10:42:19 PM UTC
Build Host  : buildvm-18.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/boto/boto
Summary     : A simple, lightweight interface to Amazon Web Services
Description :
Boto is a Python package that provides interfaces to Amazon Web Services.
It supports over thirty services, such as S3 (Simple Storage Service),
SQS (Simple Queue Service), and EC2 (Elastic Compute Cloud) via their
REST and Query APIs.  The goal of boto is to support the full breadth
and depth of Amazon Web Services.  In addition, boto provides support
for other public services such as Google Storage in addition to private
cloud systems like Eucalyptus, OpenStack and Open Nebula.
```

The previous 2.25.0 version built by CentOS is working just fine

```
Name        : python-boto
Arch        : noarch
Version     : 2.25.0
Release     : 2.el7.centos
Size        : 7.5 M
Repo        : installed
Summary     : A simple lightweight interface to Amazon Web Services
URL         : https://github.com/boto/boto
License     : MIT
Description : Boto is a Python package that provides interfaces to Amazon Web Services.
            : It supports over thirty services, such as S3 (Simple Storage Service),
            : SQS (Simple Queue Service), and EC2 (Elastic Compute Cloud) via their
            : REST and Query APIs.  The goal of boto is to support the full breadth
            : and depth of Amazon Web Services.  In addition, boto provides support
            : for other public services such as Google Storage in addition to private
            : cloud systems like Eucalyptus, OpenStack and Open Nebula.
```

I guess short term workaround is to force installation of 2.25.0 package from CentOS.  If this isn't the right place for package bugs please let me know where to file them and I will.  Thanks.

**Comment by gholms** [comment]
The right place to file bugs against EPEL packages is http://bugzilla.redhat.com/.  In this case you're in luck;  it has already been [filed](https://bugzilla.redhat.com/show_bug.cgi?id=1229863) and fixed.  If you're interested in helping test the fix please install it from [the build system](http://koji.fedoraproject.org/koji/buildinfo?buildID=644595) and then log in [here](https://admin.fedoraproject.org/updates/python-boto-2.38.0-2.el7) and provide feedback.  It should appear in epel-testing fairly soon as well.

**Comment by stieg** [comment]
Thanks @gholms.  I'll give it a spin.
