### ISSUE TITLE
Concurrent S3 + SQS connection problems 

### ISSUE THREAD

**Issue by CapCap** [boto/boto#3266]
This is a problem that we found on our Ubuntu (14) server, with code that works in a windows environment. This problem seems to only happen when attempting to connect to both S3 and SQS.
Python 2.7.8 windows, 2.7.6 ubuntu, and Boto 2.38 on both

Here is the code:
```python
class s3(object):    
    aws_access_key_id ="AWS_ACCESS_KEY_ID",
    aws_secret_access_key = "AWS_SECRET_ACCESS_KEY"
    bucket_name = "deepdream-input"

sqs = boto.sqs.connect_to_region( "us-east-1",
                                  aws_access_key_id = s3.aws_access_key_id ,
                                  aws_secret_access_key = s3.aws_secret_access_key,
				  debug = 2)
print( sqs.get_queue(s3.bucket_name) )

conn = boto.connect_s3(s3.aws_access_key_id, s3.aws_secret_access_key, debug = 2)
print( conn.get_bucket(s3.bucket_name) )
```

And the error:
```
Traceback (most recent call last):
  File "tester.py", line 47, in <module>
    sqs_q = sqs.get_queue('deepdream-input')
  File "/usr/local/lib/python2.7/dist-packages/boto/sqs/connection.py", line 462, in get_queue
    return self.get_object('GetQueueUrl', params, Queue)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1192, in get_object
    response = self.make_request(action, params, path, verb)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1116, in make_request
    return self._mexe(http_request)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 927, in _mexe
    request.authorize(connection=self)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 377, in authorize
    connection._auth_handler.add_auth(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto/auth.py", line 545, in add_auth
    l = ['AWS4-HMAC-SHA256 Credential=%s' % self.scope(req)]
  File "/usr/local/lib/python2.7/dist-packages/boto/auth.py", line 425, in scope
    return '/'.join(scope)
```
Adding a print shows that ```self._provider.access_key = ('AWS-KEY-IS-HERE',)```
If, at the [start of the scope method above in auth.py](https://github.com/boto/boto/blob/develop/boto/auth.py#L419), I add: 
```python
   if type(self._provider.access_key) is tuple:
            self._provider.access_key = self._provider.access_key[0]
```
Then the SQS works perfectly, but I get 403 errors from s3:
```
  File "tester.py", line 67, in <module>
    bucket = s3.get_bucket(bucket_name)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 502, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 535, in head_bucket
    raise err
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
```

When running with debug = 2, here is what I see in the headers for the S3 connection, which returns a 403: 
```
AWS ('AWS-KEY-IS-HERE',):AWS-SECRET-IS-HERE=\r\nUser-Agent: Boto/2.38.0 Python/2.7.6 Linux/3.13.0-57-generic\r\n\r\n"
```

I'm still looking into debugging this, but- Any ideas why this is happening?

**Comment by garnaat** [comment]
Is that a comma, right there at the end of that line?

    class s3(object):    
        aws_access_key_id ="AWS_ACCESS_KEY_ID",

**Comment by CapCap** [comment]
Not in the original code, no. I reinstalled boto, repulled, and it seems to have fixed the problem

**Comment by jamesls** [comment]
Glad you were able to get this working.  Closing issue.
