### ISSUE TITLE
Boto config ignores AWS_CREDENTIAL_FILE

### ISSUE THREAD

**Issue by Bekt** [boto/boto#3275]
Boto for some reason ignores the `AWS_CREDENTIAL_FILE` flag.

```py
import os
import boto
import boto.ec2

boto.set_stream_logger('boto')

print(os.environ.get('AWS_CREDENTIAL_FILE'))

c = boto.ec2.connect_to_region('us-west-2')
print(c.get_all_reservations())
```

Works fine with the default config location.
```bash
$ cat ~/.aws/credentials
[default]
aws_access_key_id = <extracted>
aws_secret_access_key = <extracted>

$ python t.py
None
[Reservation:r-xx, Reservation:r-xx]
```

Fails if the default config directory is changed and `AWS_CREDENTIAL_FILE` is specified.
```bash
$ mv ~/.aws/ ~/.bbb/

$ cat ~/.bbb/credentials
[default]
aws_access_key_id = <extracted>
aws_secret_access_key = <extracted>

$ set -x "AWS_CREDENTIAL_FILE" "/Users/dev/.bbb/credentials" 

$ python t.py
/Users/dev/.bbb/credentials
2015-07-17 19:43:12,713 boto [DEBUG]:Retrieving credentials from metadata server.
2015-07-17 19:43:13,719 boto [ERROR]:Caught exception reading instance data
Traceback (most recent call last):
  File ".../boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2015-07-17 19:43:13,729 boto [ERROR]:Unable to read instance data, giving up
Traceback (most recent call last):
  File "t.py", line 5, in <module>
    c = boto.ec2.connect_to_region('us-west-2')
  File ".../boto/ec2/__init__.py", line 66, in connect_to_region
    return region.connect(**kw_params)
  File ".../boto/regioninfo.py", line 187, in connect
    return self.connection_cls(region=self, **kw_params)
  File ".../boto/ec2/connection.py", line 103, in __init__
    profile_name=profile_name)
  File ".../boto/connection.py", line 1100, in __init__
    provider=provider)
  File ".../boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File ".../boto/auth.py", line 987, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials```
```

**Comment by jamesls** [comment]
To be consistent with boto3/AWSCLI the env var used is `AWS_SHARED_CREDENTIAL_FILE`.  Marking as feature request.

**Comment by Bekt** [comment]
I tried the same script with `AWS_SHARED_CREDENTIAL_FILE`, it's still the same problem.

**Comment by richard-scott** [comment]
I've just spent a few hours getting blocked by this ;-(

**Comment by iximeow** [comment]
Possibly related, I ran into this issue due to using both `boto` and `boto3`. The configuration syntax is slightly different for the minimal case of a single (default) profile, and the failure mode is fairly non-obvious:

* First, I used boto3 and had a configuration file at `~/.aws/credentials` in the form:
```
[default]
aws_access_key_id = ...
aws_secret_access_key = ...
```
* Then, I installed `boto` for something else, and had !Surprise! failure to use the AWS key with the above file. Copying it to `~/.boto` didn't help.
* Intentionally setting `AWS_CREDENTIAL_FILE=<non_existent_path>` warned that boto was unable to load the credential file, so clearly boto is able to see and "load" `~/.aws/credentials` and ~/.boto`.
* Patching the library to show values it sees in the credential file, I realized the internal `Credentials` dict was empty and `profile` was `None`.
* `~/.boto` seems to be checked before `~/.aws/credentials`, and adjusting `~/.boto` as follows made the AWS key properly used:
```
[Credentials]
aws_access_key_id = ...
aws_secret_access_key = ...
```

Because `~/.boto` seems to have higher precedence to `boto` and `boto3` checks `~/.aws/credentials`, both libraries can now use the credentials specified without error.

**Surprisingly** it seems the shared credentials format in http://boto.cloudhackers.com/en/latest/boto_config_tut.html , which indicates that the format with `[default]` should be acceptable, was what was being ignored by `boto`.

In my case **the fact that boto found a credential file but could not find credentials was note worthy** but not reported in any manner, resulting in a silent error.
