### ISSUE TITLE
Setting calling_format when creating connection TypeError when getting bucket

### ISSUE THREAD

**Issue by Graziano** [boto/boto#3324]
Tested in python3.4 with 2.34.0 and 2.38.0

```python
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 00:54:21)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from boto.s3.connection import S3Connection, OrdinaryCallingFormat
>>> conn = S3Connection(calling_format=OrdinaryCallingFormat)
>>> bucket = conn.get_bucket("mybucket")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "....venv/lib/python3.4/site-packages/boto/s3/connection.py", line 502, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "....venv/lib/python3.4/site-packages/boto/s3/connection.py", line 521, in head_bucket
    response = self.make_request('HEAD', bucket_name, headers=headers)
  File "....venv/lib/python3.4/site-packages/boto/s3/connection.py", line 654, in make_request
    host = self.calling_format.build_host(self.server_name(), bucket)
TypeError: build_host() missing 1 required positional argument: 'bucket'
```

**Comment by Graziano** [comment]
Similar on 2.7:
```python
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto
>>> from boto.s3.connection import S3Connection, OrdinaryCallingFormat
>>> conn = S3Connection(calling_format=OrdinaryCallingFormat)
>>> bucket = conn.get_bucket("mybucket")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/boto/s3/connection.py", line 502, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/Library/Python/2.7/site-packages/boto/s3/connection.py", line 521, in head_bucket
    response = self.make_request('HEAD', bucket_name, headers=headers)
  File "/Library/Python/2.7/site-packages/boto/s3/connection.py", line 650, in make_request
    path = self.calling_format.build_path_base(bucket, key)
TypeError: unbound method build_path_base() must be called with OrdinaryCallingFormat instance as first argument (got str instance instead)
>>>
```

**Comment by akesterson** [comment]
This appears to be due to out-of-date documentation/google results. Pass an instance instead of a class object and it works fine:

    >>> conn = S3Connection(calling_format=OrdinaryCallingFormat())

**Comment by Graziano** [comment]
It actually doesn't work for me still, but it does avoid the unhandled exception. It looks like the proper way is to pass a _string_ with the package path to the class.
