### ISSUE TITLE
SecurityGroup.copy_to_region fails when ip_protocol=-1

### ISSUE THREAD

**Issue by franckbrunet** [boto/boto#3328]
SecurityGroup.copy_to_region fails when ip_protocol=-1

I try to copy a ec2 (not VPC) security group from one region to another
When my source security group contains "All" translated into "-1"
I get:
```
Rule: -1, None, None, 172.16.0.0/12
Traceback (most recent call last):
  File "./SecurityGroupCopyRules.py", line 86, in <module>
    main(sys.argv[1:])
  File "./SecurityGroupCopyRules.py", line 76, in main
    dest_security_group.authorize(rule.ip_protocol,rule.from_port,rule.to_port,cidr_ip)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/securitygroup.py", line 203, in authorize
    dry_run=dry_run)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 3191, in authorize_security_group
    params, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidPermission.Malformed</Code><Message>Unsupported IP protocol "-1"  - supported: [tcp, udp, icmp]</Message></Error></Errors><RequestID>f8590333-71de-43d5-8aed-41a626d975e7</RequestID></Response>
```

**Comment by franckbrunet** [comment]
If the group is not in the a VPC the command will fail
