### ISSUE TITLE
UnboundLocalError: local variable 'e' referenced before assignment when I use set set_contents_from_filename for large files

### ISSUE THREAD

**Issue by Aameer** [boto/boto#3365]
I am facing an issue with boto, I was using boto 2.37.0 but even an upgrade to 2.38.0 didn't help
```
[servername]$ python3.4 manage.py shell
Python 3.4.1 (default, Oct  7 2014, 18:12:51)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from misc_scripts.crons.dropbox_integrate import get_bucket
>>> bucket = get_bucket()
 S3 connection successful
>>> k=bucket.new_key('3615/video/3615_20.mkv')
>>> k.set_contents_from_filename('3910.mkv')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/path_to_lib/lib/boto/s3/key.py", line 1357, in set_contents_from_filename
    encrypt_key=encrypt_key)
  File "/path_to_lib/indeev5/lib/boto/s3/key.py", line 1288, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/path_to_lib/lib/boto/s3/key.py", line 748, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/path_to_lib/lib/boto/s3/key.py", line 946, in _send_file_internal
    query_args=query_args
  File "/path_to_lib/lib/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/path_to_lib/lib/boto/connection.py", line 1067, in make_request
    retry_handler=retry_handler)
  File "/path_to_lib/lib/boto/connection.py", line 1025, in _mexe
    elif e:
UnboundLocalError: local variable 'e' referenced before assignment
I am using boto 2.37.0

I think there was a similar issue like this as mentioned here (#2595)

can anyone guide me on this.
thanks

**Comment by hbbtstar** [comment]
hi @Aameer! is this still an issue you're experiencing?

**Comment by Aameer** [comment]
@hbbtstar I haven't reviewed this from a long time.
