### ISSUE TITLE
UnicodeEncodeError on 502 error from Google Storage

### ISSUE THREAD

**Issue by lalinsky** [boto/boto#3449]
When GS returns a 502 error, UnicodeEncodeError gets raised, instead of a normal boto exception.

```
Traceback (most recent call last):
  File "/opt/xxx/xxx/env/src/putils/putils/jsonrpc/dispatcher.py", line 42, in dispatch
    response = self._dispatch_impl(request, mdc)
  File "/opt/xxx/xxx/env/src/putils/putils/jsonrpc/dispatcher.py", line 100, in _dispatch_impl
    result = func(*args, **kwargs)
  File "/opt/xxx/xxx/main.py", line 107, in xxx
    key.set_contents_from_file(fp, headers={'Content-Type': content_type}, rewind=True)
  File "/opt/xxx/xxx/env/local/lib/python2.7/site-packages/boto/gs/key.py", line 580, in set_contents_from_file
    self.send_file(fp, headers, cb, num_cb, size=size)
  File "/opt/xxx/xxx/env/local/lib/python2.7/site-packages/boto/gs/key.py", line 313, in send_file
    hash_algs=hash_algs)
  File "/opt/xxx/xxx/env/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/opt/xxx/xxx/env/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/opt/xxx/xxx/env/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/opt/xxx/xxx/env/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/opt/xxx/xxx/env/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
  File "/opt/xxx/xxx/env/local/lib/python2.7/site-packages/boto/exception.py", line 296, in __init__
    super(StorageResponseError, self).__init__(status, reason, body)
  File "/opt/xxx/xxx/env/local/lib/python2.7/site-packages/boto/exception.py", line 115, in __init__
    h.parseString(self.body)
  File "/opt/xxx/xxx/env/local/lib/python2.7/site-packages/boto/handler.py", line 60, in parseString
    return self.parser.parse(StringIO(content))
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1441: ordinal not in range(128)
```

This is the value of `self.body` in the exception handler:

```
u'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 502 (Server Error)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>502.</b> <ins>That\u2019s an error.</ins>\n  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That\u2019s all we know.</ins>\n'
```

What's strange is that the code is converting utf-8 `str` to `unicode` and then passes the `unicode` object to `StringIO`, which seems wrong. Shouldn't `StringIO` work on `str` objects?

**Comment by lalinsky** [comment]
The change in https://github.com/boto/boto/commit/96cd2800b6db067e503ef499486adf50ee9ca928#commitcomment-15239533 seems like the source of problem. I'm not sure what is the right fix. From py2 perspective, the conversion from `str` to `unicode` doesn't make sense. `xml.sax` expects a file-object that returns `str` objects on `read` and `json.loads` will automatically decode utf-8 `str` objects, so both parsing options are handled well without the conversion.

**Comment by lalinsky** [comment]
Something like https://github.com/Pexeso/boto/commit/d0c5ee601342fc2c03d7b6c8d810cd1e80ab4721 is one option of fixing it, but probably not your preferred solution.

**Comment by bencaine1** [comment]
I just got this error and I believe it was transient. I'm calling insert_data thousands of times, and on the 1195th time, I got this error. Any ideas on what might be causing this?

Relevant part of the traceback:
```
  File "/usr/home/perf-matrix/bazel-bin/ingest/py/ingest_script.runfiles/__main__/verily/tools/py/bq.py", line 406, in <lambda>
    error_list.extend(execute_with_retries(lambda: table.insert_data(data[start:end]),
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/bigquery/table.py", line 816, in insert_data
    data=data)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/exceptions.py", line 231, in from_http_response
    error=error_message)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1441: ordinal not in range(128)
```
