### ISSUE TITLE
cmdshell.py stacktraces if no known hosts file

### ISSUE THREAD

**Issue by smoser** [boto/boto#3545]
Without a ~/.ssh/known_hosts file, the cmdshell will stacktrace when trying to load_host_keys.
I'm not sure if any of the valid cases where a user did not have a ~/.ssh/known_hosts would be expected to work here or not, but something better than a stack trace would be nice at least.

Example of a case where you dont have a ~/.ssh/known_hosts would be if GlobalKnownHostsFile is in use or even just a different setting for UserKnownHostsFile.

Recreate is as easy as this:
$ HOME=$(mktemp -d) nosetests -v tests/unit/manage/test_ssh.py
    test_timeout (tests.unit.manage.test_ssh.TestSSHTimeout) ... ERROR

    ======================================================================
    ERROR: test_timeout (tests.unit.manage.test_ssh.TestSSHTimeout)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ubuntu/python-boto-2.38.0/tests/unit/manage/test_ssh.py",
    line 48, in test_timeout
        test = SSHClient(server)
      File "/home/ubuntu/python-boto-2.38.0/boto/manage/cmdshell.py", line 62,
    in __init__
        self._ssh_client.load_host_keys(os.path.expanduser(host_key_file))
      File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 124, in
    load_host_keys
        self._host_keys.load(filename)
      File "/usr/lib/python2.7/dist-packages/paramiko/hostkeys.py", line 95,
    in load
        with open(filename, 'r') as f:
    IOError: [Errno 2] No such file or directory:
    '/tmp/tmp.HXnpo7af51/.ssh/known_hosts'
    
    ----------------------------------------------------------------------
Ran 1 test in 0.001s

**Comment by yashie2011** [comment]
Hi, 
I am not sure if I am posting in the right place. But, I get the "no file ~/.ssh/known_hosts"  when I use boto.manage.cmdshell. I have seen the code and it seems that "ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())" is called in the _init_ module. 
Could some one let me know that issue could be resolved?
