### ISSUE TITLE
ssl.SSLError: ('The read operation timed out',) when posting to GCS

### ISSUE THREAD

**Issue by sprussell** [boto/boto#3588]
I have a script that posts .zip files to Google Cloud Storage using boto that has been working great for months (from both Linux and OSX environments).  Recently, I had a group of users request the ability to run the script from a shared Windows VM.  When running the exact same script, I am seeing ssl.SSLError: ('The read operation timed out',) when trying to post a file using set_contents_from_file().  I've seen other issues that have brought up this exception before (e.g. https://github.com/boto/boto/issues/2830) but nothing mentions this happening when posting files.  Also, unlike some others, this is not sporadic but *always* happens for me when trying to run in this environment.  Here is the stack trace:

Traceback (most recent call last):
  File "gps_data_uploader.py", line 106, in <module>
    main()
  File "gps_data_uploader.py", line 103, in main
    do_upload(options)
  File "gps_data_uploader.py", line 46, in do_upload
    upload_uri.new_key().set_contents_from_file(localfile)
  File "C:\Python27\lib\site-packages\boto\gs\key.py", line 580, in set_contents_from_file
    self.send_file(fp, headers, cb, num_cb, size=size)
  File "C:\Python27\lib\site-packages\boto\gs\key.py", line 313, in send_file
    hash_algs=hash_algs)
  File "C:\Python27\lib\site-packages\boto\s3\key.py", line 951, in _send_file_internal
    query_args=query_args
  File "C:\Python27\lib\site-packages\boto\s3\connection.py", line 668, in make_request
    retry_handler=retry_handler
  File "C:\Python27\lib\site-packages\boto\connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "C:\Python27\lib\site-packages\boto\connection.py", line 1030, in _mexe
    raise ex
ssl.SSLError: ('The read operation timed out',)

As further background, I am able to post a file using the same boto config with gsutil from the command line.  I am also able to list the bucket contents, from the exact same uri object in that python script that eventually throws the error, using:
    for obj in upload_uri.get_bucket():
        print '%s://%s/%s' % (upload_uri.scheme, upload_uri.bucket_name, obj.name)
I would have thought if it were some problem with the network config of this particular host, I wouldn't be able to access the cloud location in these other ways.

**Comment by sprussell** [comment]
As a further note: I actually am able to upload a small text file using new_key().set_contents_from_file() but not my zip file(s).  They aren't large (< 10 MB) and, as I said, it doesn't seem to be a problem when running the script elsewhere.  Any thoughts?
