### ISSUE TITLE
boto.mturk.connection.get_all_hits(): TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by clarkgrubb** [boto/boto#3598]
I get a TypeError when I call `boto.mturk.connection.get_all_hits()`.  I am using Python 3.5 on Mac OS X El Capitan with boto 2.42.  My Mechanical Turk account has one HIT assignment pending review:

    $ cat Makefile 
    .DEFAULT_GOAL := run

    ve:
    	virtualenv -p python3 ve
    	. ve/bin/activate && pip install -r requirements.txt

    run: ve
    	. ve/bin/activate && python minimal.py

    $ cat requirements.txt 
    boto==2.42.0

    $ cat minimal.py 
    import os

    from boto.mturk.connection import MTurkConnection

    AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
    AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
    SANDBOX_HOST = 'mechanicalturk.sandbox.amazonaws.com'

    connection = MTurkConnection(aws_access_key_id=AWS_ACCESS_KEY_ID,
                                 aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                 host=SANDBOX_HOST)

    print(connection.get_all_hits())

    $ make version
    uname -a
    Darwin Clarks-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
    python --version
    Python 2.7.12

    $ make
    virtualenv -p python3 ve
    Running virtualenv with interpreter /usr/local/bin/python3
    Using base prefix '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5'
    New python executable in ve/bin/python3.5
    Also creating executable in ve/bin/python
    Installing setuptools, pip...done.
    . ve/bin/activate && pip install -r requirements.txt
    You are using pip version 6.1.1, however version 8.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Collecting boto==2.42.0 (from -r requirements.txt (line 1))
      Using cached boto-2.42.0-py2.py3-none-any.whl
    Installing collected packages: boto
    Successfully installed boto-2.42.0
    . ve/bin/activate && python minimal.py
    Traceback (most recent call last):
      File "minimal.py", line 14, in <module>
        print(connection.get_all_hits())
      File "/Users/clark/BN/minimial/ve/lib/python3.5/site-packages/boto/mturk/connection.py", line 324, in get_all_hits
        page_nums = self._get_pages(page_size, total_records)
      File "/Users/clark/BN/minimial/ve/lib/python3.5/site-packages/boto/mturk/connection.py", line 309, in _get_pages
        return list(range(1, pages + 1))
    TypeError: 'float' object cannot be interpreted as an integer

**Comment by yiboyang** [comment]
Got the same error; boto isn't happy with python 3. The solution was to either use python 2 with boto, or python 3 with [boto3](https://github.com/boto/boto3).

**Comment by awatts** [comment]
The problem is in `/boto/mturk/connection.py` on line 308, due to division, which changed between Python 2 and 3.

```python
pages = total_records / page_size + bool(total_records % page_size)
```

I think that if it were changed to

```python
pages = total_records // page_size + bool(total_records % page_size)
```

it should work, because you'll get an integer value from the division (and crucially the same integer value) in both Python 2 and 3.

Let's say `total_records = 123` and `page_size = 10`. In Python 2 the code on line 308, the value of `pages` is `13`. In Python 3, the value of `pages` is `13.3`. With double slash division, the value of `pages` is `13` in both. When you get to

```python
return list(range(1, pages + 1))
```

on the next line, if `pages` is a float, `range` is going to throw that `TypeError`.

**Comment by mattmccormick** [comment]
I also came across this error

**Comment by braingineer** [comment]
Easy fix. There's two errors, though.

### bug 1

On roughly ~308
`pages = total_records / page_size + bool(total_records % page_size)`

becomes

`pages = int(total_records / page_size + bool(total_records % page_size))`

### bug 2

the other is ~325, same file: 

`hit_sets = itertools.imap(get_page_hits, page_nums)`

 becomes

`hit_sets = map(get_page_hits, page_nums)` 

If no one wants to do a PR, I can do it later today or sometime soonish.
