### ISSUE TITLE
Support AWS (Asia Pacific) Mumbai Region (ap-south-1)

### ISSUE THREAD

**Issue by boazjohn** [boto/boto#3610]
I'm getting errors while using region as ap-south-1. Guess it's not support in all sections.

> ```
> botocore  - v1.4.31
> boto - v2.42.0
> ```

I was using SaltStack and created an issue there, but apparently it's related to boto2 - [https://github.com/saltstack/salt/issues/36438](https://github.com/saltstack/salt/issues/36438)

Stacktrace for `boto_asg.present`/`boto_lc.present`:

```
 An exception occurred in this state: Traceback (most recent call last):                                                                                               File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call                                                                                             **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_asg.py", line 467, in present
                  asg = __salt__['boto_asg.get_config'](name, region, key, keyid, profile)                                                                                          File "/usr/lib/python2.7/dist-packages/salt/modules/boto_asg.py", line 119, in get_config
                  conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/dist-packages/salt/utils/boto.py", line 189, in get_connection                                                                               'valid.'.format(region))
              SaltInvocationError: Region "ap-south-1" is not valid.
```

I didn't have problems creating security groups (boto_secgroup.present) or ELBs (boto_elb.present).

**Comment by boazjohn** [comment]
Seems this is related to ASG functions.
