### ISSUE TITLE
ImportError: No module named regions.regions

### ISSUE THREAD

**Issue by drcraig** [boto/boto#3683]
With 2.46.0, I am unable to import anything without getting an import error.

In a fresh Python 2.7.12 virtualenv with only boto installed

```
>>> import boto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/v/local/lib/python2.7/site-packages/boto/__init__.py", line 28, in <module>
    from boto.storage_uri import BucketStorageUri, FileStorageUri
  File "/home/ubuntu/v/local/lib/python2.7/site-packages/boto/storage_uri.py", line 27, in <module>
    from boto.s3.deletemarker import DeleteMarker
  File "/home/ubuntu/v/local/lib/python2.7/site-packages/boto/s3/__init__.py", line 26, in <module>
    from boto.regioninfo import RegionInfo, get_regions
  File "/home/ubuntu/v/local/lib/python2.7/site-packages/boto/regioninfo.py", line 28, in <module>
    from boto.endpoints import BotoEndpointResolver
  File "/home/ubuntu/v/local/lib/python2.7/site-packages/boto/endpoints.py", line 13, in <module>
    import boto.vendored.regions.regions as _regions
ImportError: No module named regions.regions
```

**Comment by acaire** [comment]
Fixed in https://github.com/boto/boto/issues/3681

**Comment by JordonPhillips** [comment]
You will need to upgrade to 2.46.1
