### ISSUE TITLE
boto broken on travis

### ISSUE THREAD

**Issue by esc** [boto/boto#3717]
```
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/moto/__init__.py", line 9, in <module>
    from .autoscaling import mock_autoscaling  # flake8: noqa
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/moto/autoscaling/__init__.py", line 2, in <module>
    from .models import autoscaling_backends
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/moto/autoscaling/models.py", line 2, in <module>
    from boto.ec2.blockdevicemapping import BlockDeviceType, BlockDeviceMapping
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
AttributeError: module 'boto' has no attribute 'plugin'
```

Um... help?

**Comment by MaybeS** [comment]
same here

**Comment by esc** [comment]
I fixed it by turning off sudo.

On 14 April 2017 21:58:20 CEST, "bae jiun, maybe" <notifications@github.com> wrote:
>same here
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/boto/boto/issues/3717#issuecomment-294224776

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MaybeS** [comment]
I fixed it by boto==2.38.0

but i'm meet error like #3413 and [gensim#554](https://github.com/RaRe-Technologies/gensim/issues/554)

**Comment by esc** [comment]
Started having this issue again, doing `sudo=false` is no longer an option.

**Comment by juliedavila** [comment]
I was able to fix this by setting the environment variable `BOTO_CONFIG=null`

**Comment by karantan** [comment]
`sudo=false` worked for me. Before I had it `sudo=required` but I actually didn't need it.

**Comment by akameron** [comment]
`sudo: false` worked for our build. It was not set at all.

**Comment by bjherger** [comment]
Was able to fix by adding `sudo: false` to last line of .travis.yml`

**Comment by stefan-squareweave** [comment]
In my case it looks like the issue is Boto (version 2.48.0) running under python3 in a virtualenv decides that it should search for plugins in the system's regular python path. It ends up trying to eval this file: `/usr/lib/python2.7/dist-packages/google_compute_engine/boto/compute_auth.py` which in turn imports the google_compute_engine package. This doesn't exist in the python3 module list. The full stacktrace follows:

```python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/storages/backends/s3boto.py", line 25, in <module>
    from boto import __version__ as boto_version
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "/usr/lib/python2.7/dist-packages/google_compute_engine/boto/compute_auth.py", line 19, in <module>
    from google_compute_engine import logger
ImportError: No module named 'google_compute_engine'
```

I get several other stacktraces including one similar to the OP's, but I believe the above is the core issue here. 

The fix I think would be to limit Boto's plugin searches to its current virtualenv (somehow), or get rid of the automagic plugin finder in favour of manually selecting plugins.

A work-around in my case is to simply `pip install google-compute-engine` in the python3 virtualenv.

**Comment by DailyDreaming** [comment]
Had this error before (Oct 2) and `sudo: false` fixed it.  Now it's happening again on our travis build for unknown reasons.

Edit: Using @defionscode 's suggestion of `BOTO_CONFIG=/dev/null` fixed it this time.
