### ISSUE TITLE
Google storage: error while reading gzipped files

### ISSUE THREAD

**Issue by stmos** [boto/boto#3745]
Hi,

here are the libraries I am currently using for a project:
boto==2.48.0
django-storages==1.6.3
django-pipeline==1.6.13

Reading and storing files in Google Cloud Storage is working fine as long as I don't set the GS_IS_GZIPPED value to True.

If I enable gzip compression, I can see that files are stored compressed when running 'collectstatic' in Google Cloud Storage.

The following command from shell will fail:

```
> from django.contrib.staticfiles.storage import staticfiles_storage
> file = staticfiles_storage.open('css/assets.css')
> content = file.read()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/build/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 105, in read
    return super(S3BotoStorageFile, self).read(*args, **kwargs)
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
```

Reading files that are not compressed works fine.

STATICFILES_STORAGE uses the following custom class:

```
class StaticRootGSBotoStorage(PipelineMixin, ManifestFilesMixin, GSBotoStorage):
    try:
        location = settings.GS_STATIC_LOCATION
    except:
        pass
```

Anyone with the same issue? Thanks.

**Comment by stmos** [comment]
This issue can actually be fixed in django-storages. Closing.
