### ISSUE TITLE
tests/unit/glacier/test_writer.py has become broken for pypy

### ISSUE THREAD

**Issue by markhjelm** [boto/boto#3761]
Commit 8bd2baf8 has exposed a new failure mode for test_writer.py when run by pypy (only). 

nose command: tests/test.py -a !notdefault -x -vv tests/unit/glacier/test_writer.py
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
test_one_part_no_resume (tests.unit.glacier.test_writer.TestResume) ... FAIL

======================================================================
FAIL: test_one_part_no_resume (tests.unit.glacier.test_writer.TestResume)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/markhjelm/git/pure/boto/tests/unit/glacier/test_writer.py", line 240, in test_one_part_no_resume
    self.check_no_resume(b'1234')
  File "/usr/local/google/home/markhjelm/git/pure/boto/tests/unit/glacier/test_writer.py", line 237, in check_no_resume
    self.vault, resume_upload_part_calls, data_tree_hashes, len(data))
  File "/usr/local/google/home/markhjelm/git/pure/boto/tests/unit/glacier/test_writer.py", line 108, in check_mock_vault_calls
    upload_part_calls, any_order=True)
  File "/tmp/pypy/home/travis/virtualenv/pypy2.7-5.8.0/site-packages/mock/mock.py", line 998, in assert_has_calls
    ), cause)
  File "/tmp/pypy/home/travis/virtualenv/pypy2.7-5.8.0/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: (call.layer1.upload_part(sentinel.vault_name, sentinel.upload_id, '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', '0eb0115a1d1f0a107cf736a6f583d1d52262550c95a83cf581ef0e0f950ab76b', (0, 3), '1234'),) not all found in call list

**Comment by markhjelm** [comment]
A recent unrelated boto commit exposed a new failure mode in this test when running against pypy (only). The breakage appears to be due to an underlying change in the behavior of pypy, expressed when using assert_has_calls() from mock.py. Investigation revealed that __eq__ in _Call from mock.py is not symmetric (intentionally, related to wildcard tests), and pypy (now?) passes the arguments to __eq__ in the remove method for the built-in list type in a different order than other Python implementations. Including ".layer1.upload_part" in the name of a _Call triggers the problem when mock.py compares it with the unnamed _Call instance it captures internally. Removing the extended name enables the test to perform correctly when run with both pypy and Python 2.7.6 (and presumably others).

See https://bitbucket.org/pypy/pypy/issues/2352/list__contains__-compares-objects-in-wrong and https://bitbucket.org/pypy/pypy/commits/4bd027dc94a24293c504f60f1cea9070a79af0e0 for possibly related pypy changes (although I didn't fully trace the timeline).

Fix and pull request on the way.

**Comment by markhjelm** [comment]
https://github.com/boto/boto/pull/3762 contains the fix.

**Comment by markhjelm** [comment]
And has been merged in. Any issues or concerns, please comment here.
