### ISSUE TITLE
No Support for new eu-west-3 (Paris) region

### ISSUE THREAD

**Issue by maishsk** [boto/boto#3783]
When trying to access some of the API's in the new Paris region I am receiving messages such as

"msg": "Region eu-west-3 does not seem to be available for aws module boto.ec2. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path"

**Comment by ebarault** [comment]
thanks @maishsk for your PR, while we're waiting to be reviewed by boto's core team, i successfully cloned you repo, installed manually and used it with `ec2.py` (ansible dynamic inventory for aws) in **eu-west-3** 
👍 💯

**Comment by nmozen** [comment]
I also need it. Is there an ETA to include that ?

**Comment by lkoniecki** [comment]
Any ETA for the support for eu-west-3 region in the official release of boto?

**Comment by k-lisiecki** [comment]
Hi,
this is currently one of the most desirable AWS regions...
Any update on this issue?

**Comment by wojtas911** [comment]
+1

**Comment by maishsk** [comment]
Abandoned the previous PR and submitted an new one.

Please review

**Comment by wojtas911** [comment]
Test successfully with boto
pip freeze |grep boto
boto==2.48.0
NOTE:
I did check  ONLY endpoint for EC2

**Comment by wojtas911** [comment]
Hi @pkaramol 
I have changed boto endpoint file with that one in this issue.
Just download a filehttps://github.com/maishsk/boto/commit/2d475c6150f0ee011fd8ff5071300a8261e0231f

and  lookup the doc:
http://boto.cloudhackers.com/en/latest/boto_config_tut.html
You can export BOTO_ENDPOINTS or make point file in boto.conf

**Comment by stormm2138** [comment]
Thanks @wojtas911 Note setting endpoints_path in my .boto conf file and setting the BOTO_ENDPOINTS to point to the new endpoints yielded an error:

```python
>>> from boto.ec2 import connect_to_region
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python-2.7.5/lib/python2.7/site-packages/boto/ec2/__init__.py", line 31, in <module>
    RegionData = load_regions().get('ec2', {})
  File "/opt/python-2.7.5/lib/python2.7/site-packages/boto/regioninfo.py", line 113, in load_regions
    endpoints = merge_endpoints(endpoints, additional)
  File "/opt/python-2.7.5/lib/python2.7/site-packages/boto/regioninfo.py", line 80, in merge_endpoints
    defaults[service].update(region_info)
TypeError: 'int' object is not iterable
```
Overwriting the original endpoints in 

    /opt/python-2.7.5/lib/python2.7/site-packages/boto/endpoints.json

Worked though

**Comment by wojtas911** [comment]
Hi,
@stormm2138 
The file in path "/opt/python-2.7.5/lib/python2.7/site-packages/boto/endpoints.json" and BOTO_ENDPOINTS  evn were the same ?
If yes let me know, I will test that out and if that problem can be replicated the issue should be raised.

**Comment by stormm2138** [comment]
No originally I left /opt/python-2.7.5/lib/python2.7/site-packages/boto/endpoints.json untouched and did:

    export BOTO_ENDPOINTS=/root/endpoints_new.json # This is the updated endpoints file

So basically there was an error when merging the new endpoints into the existing endpoints. I saw this as well when setting:

    endpoints_path = /root/endpoints_new.json

In the boto conf (instead of the export).

Unsetting BOTO_ENDPOINTS and removing the conf entry and Overwriting /opt/python-2.7.5/lib/python2.7/site-packages/boto/endpoints.json with the new endpoint file worked fine. The only differences in the endpoint files were the new eu-west-3 region lines. Boto version 2.48.0

**Comment by talset** [comment]
Same issue as stormm2138 with boto `2.49.0`

I can't use BOTO_ENDPOINTS because of a merging fail, so I had to Overwriting my `/usr/local/lib/python2.7/dist-packages/boto/endpoints.json`

it is pretty nasty to only be able to use the "new (18 dec 2017)" `west-3` region

The issue is open since dec 2017, could someone have a look ?

**Comment by talset** [comment]
up

**Comment by z0ph** [comment]
up

**Comment by gangamaha** [comment]
Boto 2.48 not exactly the same west-3 issue but along the comments of stormm2138 , I am trying to use custom region and endpoint(we use cloud offering similar to aws including their cli), this is my custom endpoint.json

{
  "partitions" : [ {
    "defaults" : {
      "hostname" : "{service}.{region}.{dnsSuffix}",
      "protocols" : [ "https" ],
      "signatureVersions" : [ "v4" ]
    },
    "dnsSuffix" : "objectstorage.service.networklayer.com",
    "partition" : "cos-s3",
    "partitionName" : "COS S3 Standard",
    "regionRegex" : "^(cos)\\-\\w\\-\\d$",
    "regions" : {
      "cos-monitoring" : {
        "description" : "COS S3 monitoring"
      }
    },
    "services" : {
      "cos-s3" : {
        "defaults" : {
          "protocols" : [ "http", "https" ],
          "signatureVersions" : [ "s3v4" ]
        },
        "endpoints" : {
          "cos-monitoring" : {
            "hostname" : "172.16.0.121",
            "signatureVersions" : [ "s3", "s3v4" ]
          }
        }
      }
    }
  } ],
  "version" : 3
}
and when I say endpoint_url = <file_path> in /etc/boto.cfg [Boto] section and run a custom script to connect to region or list regions I get error
    defaults[service].update(region_info)
TypeError: 'int' object is not iterable
but if I add the region and endpoint to boto default endpoint.json file it can get region details

**Comment by tammytankian** [comment]
up
Tried to update to 2.49, still having problems :(

**Comment by tambnguyen** [comment]
Same. Is there a beta version we can use?

**Comment by maishsk** [comment]
I understand the frustration here  from all parties involved - but unfortunately - personally do not have merge permissions to the repo - still waiting on the merge for https://github.com/boto/boto/pull/3794

**Comment by cjuif** [comment]
Even when updating endpoints.json file in site-package, I still get the error: 
`region name: eu-west-3 likely not supported, or AWS is down.  connection to region failed.`

`pip freeze | grep boto
boto==2.48.0
botocore==1.10.81`

Tested with boto-2.48.0 and boto 2.49.0

**Comment by talset** [comment]
@mfschwartz maybe ? or @dstufft ?

**Comment by sachin-0chain** [comment]
TASK [amipacker : Launch ami-0370f4064dbc392b9 in paris] *******************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Region eu-west-3 does not seem to be available for aws module boto.ec2. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path"}
        to retry, use: --limit @/Volumes/work/0CHAIN/codebox/0chain/awsnet/cookbook/amipacker.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=60   changed=0    unreachable=0    failed=1

**Comment by z0ph** [comment]
Hello,

I think you can check with this config (told me by an AWS employee)

`[Boto] use_endpoint_heuristics = True`

> use_endpoint_heuristics:
>   | Allows using endpoint heuristics to guess endpoints for regions that aren’t built in. This can also be specified with the BOTO_USE_ENDPOINT_HEURISTICS environment variable.

http://boto.cloudhackers.com/en/latest/boto_config_tut.html

**Comment by sachin-0chain** [comment]
Setting BOTO_USE_ENDPOINT_HEURISTICS=True fixes the problem and enables Paris. Thank you.

**Comment by arhue** [comment]
The above fix worked for me. I however had to update boto with pip.
