### ISSUE TITLE
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request

### ISSUE THREAD

**Issue by rahul6612** [boto/boto#3791]
##  i am getting this error my region is mumbai
please tell me the solution my boto version is 2.42.0
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>61E7C278C090239B</RequestId><HostId>LTqpLnqJEi2xwIQ/dDq71JwldwCFiZZh8lGsb7Z5HDJO798g0TM04PdHsALX3t8xEmqT7/997TM=</HostId></Error>

**Comment by xalpy** [comment]
2020-01-29T17:54:39.811747+00:00 app[web.1]: Traceback (most recent call last):
2020-01-29T17:54:39.811749+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-01-29T17:54:39.811751+00:00 app[web.1]: response = get_response(request)
2020-01-29T17:54:39.811753+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-01-29T17:54:39.811756+00:00 app[web.1]: response = self.process_exception_by_middleware(e, request)
2020-01-29T17:54:39.811757+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-01-29T17:54:39.811761+00:00 app[web.1]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-01-29T17:54:39.811763+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 606, in wrapper
2020-01-29T17:54:39.811765+00:00 app[web.1]: return self.admin_site.admin_view(view)(*args, **kwargs)
2020-01-29T17:54:39.811767+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
2020-01-29T17:54:39.811769+00:00 app[web.1]: response = view_func(request, *args, **kwargs)
2020-01-29T17:54:39.811771+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
2020-01-29T17:54:39.811773+00:00 app[web.1]: response = view_func(request, *args, **kwargs)
2020-01-29T17:54:39.811775+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
2020-01-29T17:54:39.811777+00:00 app[web.1]: return view(request, *args, **kwargs)
2020-01-29T17:54:39.811779+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1637, in change_view
2020-01-29T17:54:39.811781+00:00 app[web.1]: return self.changeform_view(request, object_id, form_url, extra_context)
2020-01-29T17:54:39.811783+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
2020-01-29T17:54:39.811784+00:00 app[web.1]: return bound_method(*args, **kwargs)
2020-01-29T17:54:39.811786+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
2020-01-29T17:54:39.811789+00:00 app[web.1]: response = view_func(request, *args, **kwargs)
2020-01-29T17:54:39.811791+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
2020-01-29T17:54:39.811793+00:00 app[web.1]: return self._changeform_view(request, object_id, form_url, extra_context)
2020-01-29T17:54:39.811794+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1561, in _changeform_view
2020-01-29T17:54:39.811796+00:00 app[web.1]: self.save_model(request, new_object, form, not add)
2020-01-29T17:54:39.811798+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1088, in save_model
2020-01-29T17:54:39.811800+00:00 app[web.1]: obj.save()
2020-01-29T17:54:39.811802+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
2020-01-29T17:54:39.811804+00:00 app[web.1]: force_update=force_update, update_fields=update_fields)
2020-01-29T17:54:39.811806+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
2020-01-29T17:54:39.811808+00:00 app[web.1]: force_update, using, update_fields,
2020-01-29T17:54:39.811829+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/base.py", line 848, in _save_table
2020-01-29T17:54:39.811832+00:00 app[web.1]: for f in non_pks]
2020-01-29T17:54:39.811834+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/base.py", line 848, in <listcomp>
2020-01-29T17:54:39.811836+00:00 app[web.1]: for f in non_pks]
2020-01-29T17:54:39.811838+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/fields/files.py", line 288, in pre_save
2020-01-29T17:54:39.811840+00:00 app[web.1]: file.save(file.name, file.file, save=False)
2020-01-29T17:54:39.811842+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/fields/files.py", line 87, in save
2020-01-29T17:54:39.811844+00:00 app[web.1]: self.name = self.storage.save(name, content, max_length=self.field.max_length)
2020-01-29T17:54:39.811846+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 52, in save
2020-01-29T17:54:39.811848+00:00 app[web.1]: return self._save(name, content)
2020-01-29T17:54:39.811850+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/storages/backends/s3boto.py", line 425, in _save
2020-01-29T17:54:39.811851+00:00 app[web.1]: key = self.bucket.get_key(encoded_name)
2020-01-29T17:54:39.811853+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/boto/s3/bucket.py", line 193, in get_key
2020-01-29T17:54:39.811855+00:00 app[web.1]: key, resp = self._get_key_internal(key_name, headers, query_args_l)
2020-01-29T17:54:39.811857+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/boto/s3/bucket.py", line 232, in _get_key_internal
2020-01-29T17:54:39.811859+00:00 app[web.1]: response.status, response.reason, '')
2020-01-29T17:54:39.811861+00:00 app[web.1]: boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request

i got this exception when try upload photo on my django app


settings.py 

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

AWS_QUERYSTRING_AUTH = False
AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
AWS_STORAGE_BUCKET_NAME = os.environ['S3_BUCKET_NAME']
MEDIA_URL = 'http://%s.s3.amazonaws.com/media/' % AWS_STORAGE_BUCKET_NAME
DEFAULT_FILE_STORAGE = "storages.backends.s3boto.S3BotoStorage"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

s3-bucket
![image](https://user-images.githubusercontent.com/50137288/73383521-8af77b80-42da-11ea-99c3-58a3b88ca5fc.png)
