### ISSUE TITLE
InvalidAction: DescribeLaunchConfigurations

### ISSUE THREAD

**Issue by sameergautam** [boto/boto#3812]
I'm getting an issue with Launch Configuration while using Ansible's [`ec2_lc`](http://docs.ansible.com/ansible/latest/modules/ec2_lc_module.html) module. Listed below are few more details:

<details>
<summary>Backtrace</summary>

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/b_/g8r_f0cx0bdb0vb5c2m55lth0000gn/T/ansible_jVpiEI/ansible_module_ec2_lc.py", line 498, in create_launch_config
    launch_configs = connection.describe_launch_configurations(LaunchConfigurationNames=[name]).get('LaunchConfigurations')
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidAction) when calling the DescribeLaunchConfigurations operation: The action DescribeLaunchConfigurations is not valid for this web service.

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "error": {
        "code": "InvalidAction",
        "message": "The action DescribeLaunchConfigurations is not valid for this web service."
    }
...
```
</details>

<details>
<summary>Ansible Play </summary>

```yaml
- name: Create Launch Configuration
  ec2_lc:
    region: "{{ region }}"
    name: "ansible-launch-config"
    image_id: "{{ image_id }}"
    instance_type: "{{ instance_type }}"
    security_groups: "{{ security_groups }}"
    state: present

```
</details>
<details>
<summary>System Details</summary>

```
ansible --version
ansible 2.5.0
```
```
boto version: 
import boto; print(boto.__version__)
2.48.0
```

**Comment by Bustead** [comment]
Hi @sameergautam how did you go with this issue?
