### ISSUE TITLE
Lambda boto cannot process API Gateway v2 WebSocket

### ISSUE THREAD

**Issue by jon-trust** [boto/boto#3905]
When backing up a API Gateway WebSocket with a Python 3.8 Lambda, the lambda is not able to send a well-formed response to API-GW. The same code works in Node.js, so the infrastructure is correct.

The code
```python
import json
import boto3

def lambda_handler(event, context):
    client = boto3.client('apigatewaymanagementapi')
    response = client.post_to_connection(Data=b'Hello 2!',ConnectionId=event['requestContext']['connectionId'])
    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }
```

Got the following error
```
[ERROR] EndpointConnectionError: Could not connect to the endpoint URL: "https://execute-api.us-west-2.amazonaws.com/@connections/OlBCJe-5PHcCIEw%3D"
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 11, in lambda_handler
    response = client.post_to_connection(Data=b'Hello from Lambda 2!',ConnectionId=event['requestContext']['connectionId'])
  File "/var/runtime/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 612, in _make_api_call
    http, parsed_response = self._make_request(
  File "/var/runtime/botocore/client.py", line 632, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/var/runtime/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/var/runtime/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/var/runtime/botocore/endpoint.py", line 228, in _needs_retry
    responses = self._event_emitter.emit(
  File "/var/runtime/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/runtime/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/var/runtime/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/var/runtime/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/var/runtime/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/var/runtime/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/var/runtime/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/var/runtime/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/var/runtime/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/var/runtime/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/var/runtime/botocore/endpoint.py", line 244, in _send
    return self.http_session.send(request)
  File "/var/runtime/botocore/httpsession.py", line 283, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
```

I suspect an issue in the translation of the URL of the endpoint (first line of the error). It should be an "=" at the very end of the URL, and not its encoded equivalent "%3D".

**Comment by wowzoo** [comment]
refer to the link below.

https://github.com/boto/boto3/issues/1914

it might be helpful.

**Comment by kdaily** [comment]
Hi there,

This package is deprecated and no longer supported. Please review the deprecation notice for migration to `boto3`. Thanks!

https://github.com/boto/boto#deprecation-notice
