### ISSUE TITLE
broken pipe error, non US-Standard region

### ISSUE THREAD

**Issue by jkarneges** [boto/boto#621]
My S3 region is Northern California, aka us-west-1.  Uploads almost always fail after some timeout period, even if the files are "small" (<200K).  I'm using boto 2.2.2 and python 2.7.2.  The uploads are being made from an EC2 machine in the same region.

Here's the exception I always get:

``` python
Traceback (most recent call last):
  File "backup_to_s3.py", line 25, in <module>
    k.set_contents_from_filename("/tmp/%s" % dumpfile)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 969, in set_contents_from_filename
    encrypt_key=encrypt_key)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 902, in set_contents_from_file
    size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 660, in send_file
    query_args=query_args)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 449, in make_request
    override_num_retries=override_num_retries)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 829, in make_request
    return self._mexe(http_request, sender, override_num_retries)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 794, in _mexe
    raise e
socket.error: [Errno 32] Broken pipe
```

I used is_secure=False and tcpdump to inspect what was happening.  It looks like by default requests from boto are sent to the primary S3 host, which then responds with redirects to the correct region using HTTP code 307.  While boto does honor the 307 for some exchanges, it seems not to for PUT, or at least not consistently, and so I think this is what is causing the failures.

Passing host="s3-us-west-1.amazonaws.com" to S3Connection's constructor solved the problem for me.

**Comment by shredding** [comment]
Just for reference: If you are using django-storages or django-storages-redux, setting AWS_S3_HOST to the correct endpoint (http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) fixed it for me.

**Comment by bedspax** [comment]
+1

**Comment by btoueg** [comment]
+1 python 3.4 boto 2.36.0

**Comment by klinkin** [comment]
+1 python 2.7.9 boto 2.36.0

**Comment by pipermerriam** [comment]
+1 python 2.7.9 boto 2.36.0 osx

**Comment by netinept** [comment]
+1 This issue is still ongoing with python 2.7.6 and boto 2.38.0 on OS 10.10.3 and Heroku.

For me this issue always happens with jquery.js from `[project name]/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.js'`

I've also found a recent [StackOverflow question](http://stackoverflow.com/questions/29552242/using-djangos-collectstatic-with-boto-s3-throws-error-32-broken-pipe-after-a) with the same issue.

I have tried setting the region and even creating a new bucket on the default region, but that still fails.

```
(venv)kylefalconer@Kyles-MacBook-Air ~/g/plog> python manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings.

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/base.css'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/changelists.css'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/forms.css'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/ie.css'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/login.css'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/rtl.css'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/widgets.css'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/changelist-bg.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/changelist-bg_rtl.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/default-bg-reverse.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/default-bg.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/deleted-overlay.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-no.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-unknown.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-yes.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_addlink.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_alert.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_calendar.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_changelink.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_clock.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_deletelink.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_error.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_searchbox.png'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_success.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-delete-8bit.png'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-delete.png'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-restore-8bit.png'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-restore.png'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-splitter-bg.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/nav-bg-grabber.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/nav-bg-reverse.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/nav-bg-selected.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/nav-bg.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/selector-icons.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/selector-search.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/sorting-icons.gif'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-add.png'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-arrowright.png'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_off.png'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_on.png'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/actions.js'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/actions.min.js'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/calendar.js'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/collapse.js'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/collapse.min.js'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/core.js'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/inlines.js'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/inlines.min.js'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.init.js'
Copying '/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.js'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 107, in collect
    handler(path, prefixed_path, storage)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 315, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/django/core/files/storage.py", line 64, in save
    name = self._save(name, content)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/storages/backends/s3boto.py", line 392, in _save
    self._save_content(key, content, headers=headers)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/storages/backends/s3boto.py", line 403, in _save_content
    rewind=True, **kwargs)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/Users/kylefalconer/git/plog/venv/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
socket.error: [Errno 32] Broken pipe
(venv)kylefalconer@Kyles-MacBook-Air ~/g/plog> touch .boto
```

**Comment by coolharsh55** [comment]
Using a boto-config with region and http-timeout did not give me errors (no broken pipes or sockets).

**Comment by bedspax** [comment]
can you share your boto-config and http-timeout stuff? @coolharsh55 thx.

**Comment by coolharsh55** [comment]
Hi,
Thanks for taking the time out to reply.

I created a different S3 user and it started working.
Unfortunately, I did not save the boot config that was not working.
And frankly, I have forgotten what the error could have been.
I suspect that the problem was with my bucket being in europe-west region, I read about some others having similar errors as well. I inserted the appropriate bucket region and I think that could be what worked.

If you need any help, I’ll be glad to do so.
Cheers,
H

On 15 May 2015 at 01:14:09, bedspax (notifications@github.com) wrote:

can you share your boto-config and http-timeout stuff? @coolharsh55 thx.

—
Reply to this email directly or view it on GitHub.

-- 
Harshvardhan J. Pandit
http://harshp.com

**Comment by ddahan** [comment]
+1 for shredding tip! Thanks!

**Comment by andessen** [comment]
I wanted to confirm this. Exactly same annoying situation when uploading certain PDF files of a certain size. Adding host="s3-us-west-2.amazonaws.com" to my S3Connection call fixed it.

Please fix!

**Comment by rlam3** [comment]
+1 adding host is not working for me....

**Comment by radiovisual** [comment]
This is happening for me as well. I have a bucket in the Ireland region `https://s3-eu-west-1.amazonaws.com`. It fails 100% of the time on jquery.js just like the user @netinept [reported above](https://github.com/boto/boto/issues/621#issuecomment-96636238). 

Using: 
```
boto==2.38.0
django-storages==1.1.8
```

**Comment by theDrGray** [comment]
+1

-OSX 10.10.5
-python 2.7.9
-boto 2.38.0

**Comment by talumbau** [comment]
+1
- OSX 10.10.5
- python 2.7.11
- boto 2.39

using django-storages, I found the same as others above: if I set `AWS_S3_HOST` to `s3-us-west-2.amazonaws.com` everything worked as normal. The strange thing s that I have a bucket in the same region where everything worked fine last week. In fact, I can reproduce and get `collectstatic` to not work with the new bucket and work with old bucket (without specifying `AWS_S3_HOST`). Very odd.

**Comment by DataGreed** [comment]
But Amazon states that S3 should be region-independable

**Comment by xuchen81** [comment]
+1  Same issue here. 
`boto==2.40.0`

**Comment by introbig** [comment]
adding the host as above fixed my error too

**Comment by kristiandrucker** [comment]
Edit and add this line to your `settings.py` file
``` python
AWS_S3_HOST = "s3-eu-west-1.amazonaws.com"
```

**Comment by KophyGiddie** [comment]
Adding the line below to my settings fixed everything

AWS_S3_HOST = "s3-eu-west-1.amazonaws.com"

This applies to Ireland. You can check the list below for other regions

us-west-1: s3-us-west-1.amazonaws.com
us-west-2: s3-us-west-2.amazonaws.com
sa-east-1: s3.sa-east-1.amazonaws.com
eu-west-1: s3-eu-west-1.amazonaws.com
ap-southeast-1: s3-ap-southeast-1.amazonaws.com
ap-southeast-2: s3-ap-southeast-2.amazonaws.com
ap-northeast-1: s3-ap-northeast-1.amazonaws.com
